mozilla/release-services

.gitignore
src/shipit_frontend/src/App/ReleaseDashboard.elm

Support WedData to fetch analysis

Shipit: WebData

---

src/shipit_dashboard/README.md
src/shipit_dashboard/bootstrap.sh
src/shipit_dashboard/shipit_dashboard/__init__.py
src/shipit_dashboard/shipit_dashboard/api.py
src/shipit_dashboard/shipit_dashboard/encoder.py
src/shipit_dashboard/shipit_dashboard/swagger.yml
src/shipit_dashboard/shipit_dashboard/workflow.py
src/shipit_frontend/src/App.elm
src/shipit_frontend/src/App/ReleaseDashboard.elm
src/shipit_frontend/src/App/User.elm
src/shipit_frontend/src/App/Utils.elm
src/shipit_frontend/src/index.js
src/shipit_frontend/src/index.scss

This PR support the TaskCluster authentication, for both frontend and backend (wip).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/garbas/mozilla-releng/43)

Shipit: Authenticated requests

---

src/releng_common/releng_common/auth.py
src/shipit_dashboard/shipit_dashboard/api.py
src/shipit_frontend/src/App/User.elm
src/shipit_frontend/src/index.js

I've added a generic auth process through [TC authenticateHawk](https://docs.taskcluster.net/reference/platform/auth/api-docs#authenticateHawk) in releng_common.
The elm part needs a bit more work to be generic: every request sent to a backend needs a new header (the nonce & timestamp must change).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/garbas/mozilla-releng/53)

Taskcluster HAWK auth

---

src/releng_frontend/src/trychooser/index.html

hide "back to releng services" when embedding

---

src/releng_docs/prerequirements.rst

I tested the process on an Ubuntu:
* document LVM setup
* step 5 must be run before step 4 (need nix-env before killing user profile)
* added upstart support

Pre requirements doc update

---

.gitignore
Makefile
lib/releng_common/default.nix
lib/releng_common/releng_common/auth.py
lib/releng_common/releng_common/mocks.py
lib/releng_common/tests/conftest.py
lib/releng_common/tests/test_auth.py
src/releng_clobberer/requirements_frozen.txt
src/releng_clobberer/requirements_generated.nix
src/releng_tooltool/requirements_generated.nix
src/releng_treestatus/requirements_generated.nix
src/shipit_dashboard/default.nix
src/shipit_dashboard/requirements_frozen.txt
src/shipit_dashboard/requirements_generated.nix
src/shipit_dashboard/settings.py
src/shipit_dashboard/tests/conftest.py
src/shipit_dashboard/tests/test_analysis.py
src/shipit_dashboard/tests/test_example.py
src/shipit_workflow/requirements_generated.nix

* Adds responses as a dependency
* Tests releng_common auth
* Test shipit_dashboard api

Python test cases

---

lib/elm_common/Hawk.elm
lib/elm_common/example/Example.elm
lib/elm_common/hawk.js
src/shipit_frontend/src/App/ReleaseDashboard.elm

With Http.Request body support

Shipit frontend: fully working on elm-common

---

lib/releng_common/releng_common/auth.py
lib/releng_common/releng_common/log.py
src/shipit_dashboard/settings.py

+ minor tweak on shipit_dashboard

Redirect stdlib logging to logbook

---

src/shipit_dashboard/shipit_dashboard/api.py
src/shipit_dashboard/shipit_dashboard/serializers.py
src/shipit_dashboard/tests/test_analysis.py
src/shipit_frontend/src/App/ReleaseDashboard.elm
src/shipit_frontend/src/scss/index.scss

Add extra informations and actions on bug:
* Display bug status, component & product
* Support generic bugzilla flags, always enabling qe-verify option

Uplift dashboard : Fix #175

---

src/shipit_dashboard/shipit_dashboard/api.py
src/shipit_dashboard/shipit_dashboard/models.py

Prevents current bug in production/staging (+ fixme.sql through mail)

shipit_dashboard: do not allow to create bugs without uplift comment.

---

src/releng_frontend/src/static/trychooser/index.html

This PR is trying to fix [Bug 1344144](https://bugzilla.mozilla.org/show_bug.cgi?id=1344144).

releng_frontend: add linux64-stylo

---

nix/setup.sh
src/releng_docs/index.rst
src/releng_docs/prerequirements.rst

combine changes from #189 and #247, rebased on master and added documentation how to quickstart using ``setup.sh`` script

nix: add setup script

---

.taskcluster.yml
Makefile
src/releng_docs/conf.py
src/releng_docs/contributing.rst
src/releng_docs/default.nix
src/releng_docs/deploying.rst
src/releng_docs/index.rst
src/releng_docs/services_releng.rst
src/releng_docs/services_shipit.rst
src/shipit_signoff/docs/shipit-signoffs.rst

My poor attempt to document the release process. if nothing it can be a first try.
I would love if somebody has time to review it.

releng_docs: adding documentation about deploying / releasing

---

lib/frontend_common/TaskclusterLogin.elm
src/releng_frontend/src/App.elm
src/releng_frontend/src/Main.elm
src/shipit_frontend/src/App.elm

The shipit frontend was not correctly displaying relevant informations in certain authentications cases:
* when certificate is expired
* on first login
I fixed a dummy reference bug in shipit frontend, but also add a check on certificate expiry date when loading new credentials.

Fix bug in frontend auth workfow

---

Makefile
nix/lib/default.nix
src/releng_archiver/releng_archiver/__init__.py
src/releng_archiver/releng_archiver/flask.py
src/releng_clobberer/releng_clobberer/__init__.py
src/releng_clobberer/releng_clobberer/flask.py
src/releng_mapper/releng_mapper/__init__.py
src/releng_mapper/releng_mapper/flask.py
src/releng_tooltool/releng_tooltool/__init__.py
src/releng_tooltool/releng_tooltool/flask.py
src/releng_treestatus/releng_treestatus/__init__.py
src/releng_treestatus/releng_treestatus/flask.py
src/shipit_pipeline/shipit_pipeline/__init__.py
src/shipit_pipeline/shipit_pipeline/flask.py
src/shipit_signoff/default.nix
src/shipit_signoff/shipit_signoff/__init__.py
src/shipit_signoff/shipit_signoff/flask.py
src/shipit_signoff/tests/swagger-2.0-spec.json
src/shipit_signoff/tests/test_api.py
src/shipit_uplift/README.md
src/shipit_uplift/migrations/versions/3a54bd40145f_.py
src/shipit_uplift/shipit_uplift/__init__.py
src/shipit_uplift/shipit_uplift/api.py
src/shipit_uplift/shipit_uplift/flask.py
src/shipit_uplift/shipit_uplift/serializers.py
src/shipit_uplift/tests/conftest.py

shipit_signoff: Make tests run on CI

---

src/shipit_signoff/shipit_signoff/__init__.py
src/shipit_signoff/shipit_signoff/api.py
src/shipit_signoff/shipit_signoff/api.yml
src/shipit_signoff/shipit_signoff/db_services.py
src/shipit_signoff/shipit_signoff/policies.py
src/shipit_signoff/shipit_signoff/util.py
src/shipit_signoff/tests/test_policies.py
src/shipit_signoff/tests/test_util.py

~~WIP~~ Depends on #281 and #282
Tests aren't currently run on Taskcluster, I met with @garbas a few minutes ago. He suggested a startegy that I'll implement tomorrow. 
In the meantime, here's what I currently have, @srfraser.

shipit_signoff: Enforce policy during signoff and detect if its met

---

src/releng_docs/conf.py
src/releng_docs/run.py
src/releng_docs/services_shipit.rst

Last week we met and discussed how shipit v1 and v2 would initially interact, at a deeper design level.
I've tried to convey what we agreed on via this PR.
@catlee @garbas and others, any concerns?

Shipit v1<->v2 interaction and design

---

lib/cli_common/cli_common/utils.py
src/shipit_static_analysis/shipit_static_analysis/cli.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py

Needed to fix `project-releng/services-staging-shipit-static-analysis-bot`

shipit_static_analysis: Redirect standard output from subprocess.

---

src/shipit_code_coverage/shipit_code_coverage/coverage_by_dir.py
src/shipit_frontend/src/App/CodeCoverage.elm

And display on shipit_frontend

shipit_code_coverage: Load bugs summary, refs #319

---

lib/cli_common/cli_common/pulse.py
lib/please_cli/please_cli/config.py
nix/gecko_env.nix
nix/lib/default.nix
src/shipit_pulse_listener/default.nix
src/shipit_pulse_listener/shipit_pulse_listener/cli.py
src/shipit_pulse_listener/shipit_pulse_listener/listener.py
src/shipit_risk_assessment/default.nix
src/shipit_risk_assessment/shipit_risk_assessment/bot.py
src/shipit_risk_assessment/shipit_risk_assessment/cli.py
src/shipit_static_analysis/default.nix
src/shipit_static_analysis/shipit_static_analysis/cli.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py

Pulse listener cannot rely on task execution from Taskcluster as some tasks may stay pending a long time...

shipit_pulse_listener: run as a service

---

src/shipit_static_analysis/shipit_static_analysis/workflow.py

Ping @jankeromnes if you could also review.

shipit_static_analysis: List modified files against parents.

---

src/shipit_pulse_listener/shipit_pulse_listener/listener.py

Tasks for risk assessment will only be created on mozilla-central pushes (ie. merges), and when they have a cpp related modified file only.

shipit_pulse_listener: Limit risk assesment tasks

---

lib/please_cli/please_cli/__init__.py
lib/please_cli/please_cli/update_dependencies.py

```shell
./please tools update-dependencies shipit-pulse-listener
Updating dependencies of shipit-pulse-listener: ...
```

please_cli: Add tool to update project dependencies (old update-app)

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

I'm assuming the `communicate` call in `run` will release the GIL while waiting for the command to be executed. If that's not the case, we would need to use multiprocessing.

shipit_code_coverage: Rewrite lcov files in parallel

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

shipit_code_coverage: Ignore areweslimyet suite

---

src/shipit_static_analysis/requirements.nix
src/shipit_static_analysis/requirements.txt
src/shipit_static_analysis/requirements_frozen.txt
src/shipit_static_analysis/shipit_static_analysis/config.yml
src/shipit_static_analysis/shipit_static_analysis/workflow.py

Issue #437 by @sylvestre 
I need #441 to fully test it.

shipit_static_analysis: Use configuration file to setup clang checkers

---

src/shipit_static_analysis/default.nix
src/shipit_static_analysis/shipit_static_analysis/clang.py
src/shipit_static_analysis/shipit_static_analysis/config.yml
src/shipit_static_analysis/shipit_static_analysis/workflow.py

shipit_static_analysis: Use Mozilla clang-tidy

---

src/shipit_code_coverage/shipit_code_coverage/coverage_by_dir.py

shipit_code_coverage: Support using codecov.io to generate coverage-by-dir report

---

src/shipit_frontend/src/App/CodeCoverage.elm

shipit_frontend: Don't show the directory itself when it is selected

---

lib/please_cli/please_cli/deploy.py

This is a difference between python 3 and 2

please_cli: octal, octal, octal

---

src/shipit_pulse_listener/shipit_pulse_listener/hook.py
src/shipit_pulse_listener/shipit_pulse_listener/listener.py

shipit_pulse_listener: Trigger code coverage task when a linux64-ccov build and related tests are finished

---

src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py

shipit_uplift: Get directory-specific coverage and not overall coverage

---

src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py

They are slow to reply and cause timeouts on Heroku (30s). Performing the requests in parallel should solve the timeout issues.

shipit_uplift: Use multiple threads to request code coverage information from codecov.io/coveralls.io

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

shipit_code_coverage: Try increasing the git buffer

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

The rewriting currently still needs the build to be finished before running; after #486 we won't need to wait anymore.

shipit_code_coverage: Wait build to be finished before rewriting JSVM files

---

nix/gecko_env.nix
nix/requirements_override.nix
src/shipit_static_analysis/shipit_static_analysis/batchreview.py
src/shipit_static_analysis/shipit_static_analysis/clang.py
src/shipit_static_analysis/shipit_static_analysis/cli.py
src/shipit_static_analysis/shipit_static_analysis/config.py
src/shipit_static_analysis/shipit_static_analysis/config.yml
src/shipit_static_analysis/shipit_static_analysis/workflow.py

Building #364 last requirements:

shipit_static_analysis: Add mozreview support

---

src/shipit_pulse_listener/shipit_pulse_listener/hook.py

shipit_pulse_listener: Don't cache hook definition but request it every time we trigger a new task

---

src/shipit_pulse_listener/shipit_pulse_listener/monitoring.py

shipit_pulse_listener: Fix typo in tasks monitoring.

---

nix/gecko_env.nix
src/shipit_static_analysis/shipit_static_analysis/workflow.py

Don't define MOZCONFIG in gecko-env, but let different projects define their own

---

nix/default.nix
nix/gecko_env.nix
nix/nixpkgs-mozilla.json
src/shipit_static_analysis/default.nix
src/shipit_static_analysis/shipit_static_analysis/clang.py
src/shipit_static_analysis/shipit_static_analysis/cli.py
src/shipit_static_analysis/shipit_static_analysis/lock.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py

* Simplify clang tidy header parser.
* MOZCONFIG is set in the static-analysis project
* clang 4.0
* rust 1.19.0

WIP shipit_static_analysis: Fixes to staging

---

src/shipit_code_coverage/shipit_code_coverage/utils.py
src/shipit_code_coverage/tests/test_utils.py

Waiting on #544 before rebasing.

shipit_code_coverage: Fail as soon as one thread fails

---

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py

shipit_code_coverage: Retry downloading artifacts multiple times before failing

---

src/shipit_frontend/src/App/CodeCoverage.elm

shipit_frontend: Fix 'directory' typo

---

src/shipit_uplift/shipit_uplift/api.py
src/shipit_uplift/shipit_uplift/api.yml
src/shipit_uplift/shipit_uplift/coverage.py
src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
src/shipit_uplift/shipit_uplift/coverage_summary_by_changeset_impl.py

This depends on #595. I will rebase once that one is merged.
CC @armenzg

 shipit_uplift: Add API endpoint to generate summary of coverage information for a given commit

---

src/shipit_uplift/shipit_uplift/coverage.py

The size of the response from hg.mozilla.org is reduced from ~30 kB to ~2 kB.

shipit_uplift: Use tipsonly option to reduce amount of data retrieved from hg.mozilla.org

---

src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py

shipit_uplift: Temporarily add git build changeset to coverage/changeset endpoint.

---

src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py

shipit_uplift: Cache entire backend response

---

lib/backend_common/backend_common/cors.py

Allow setting CORS resources to override CORS headers for specific API endpoints

---

src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py

shipit_uplift: Increase cache timeout to one day

---

lib/please_cli/please_cli/config.py

The  TaskCluster production secrets must be updated :
```json
...
"shipit-static-analysis": {
"STATIC_ANALYSIS_NOTIFICATIONS": [
"babadie@mozilla.com",
"sledru@mozilla.com",
"jan@mozilla.com",
"andi@mozilla.com",
"marco@mozilla.com"
],
"MOZREVIEW_ENABLED": true,
"MOZREVIEW_URL": "https://reviewboard.mozilla.org/",
"MOZREVIEW_USER": "...",
"MOZREVIEW_API_KEY": "..."
},
...
```

shipit_static_analyis: Setup production hook

---

src/releng_frontend/src/static/trychooser/index.html

Please don't merge this *right now* because the platform is not yet in try; but I wanted to submit this pull request for review as I hope we'll be commiting https://bugzilla.mozilla.org/show_bug.cgi?id=1403058 soon.

Add the MinGW platform to trychooser

---

src/shipit_static_analysis/shipit_static_analysis/clang.py
src/shipit_static_analysis/tests/test_clang.py

Fixes  #658 by skipping issues in expanded macros

shipit_static_analysis: Detect expanded macros

---

src/shipit_bot_uplift/shipit_bot_uplift/api.py
src/shipit_bot_uplift/shipit_bot_uplift/mercurial.py
src/shipit_bot_uplift/shipit_bot_uplift/merge.py
src/shipit_bot_uplift/shipit_bot_uplift/sync.py
src/shipit_static_analysis/shipit_static_analysis/batchreview.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py
src/shipit_uplift/shipit_uplift/api.py
src/shipit_uplift/tests/test_patch_status.py

shipit_*: Silent sentry

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

shipit_code_coverage: Generate report of files with no coverage

---

src/releng_frontend/src/static/trychooser/index.html

From IRC, someone new was complaining about how hard it was to figure out what to run. When he found this page, he was enlightened.

Point to the wiki page on recommended try practices

---

src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py

shipit_uplift: Use hg annotate to map lines from individual changesets to the final changeset of the push

---

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py

shipit_code_coverage: Handle failure of code coverage build

---

src/shipit_uplift/shipit_uplift/worker.py

shipit_uplift: Use SimpleWorker class to make the lru_cache actually effective

---

src/shipit_uplift/shipit_uplift/api.py
src/shipit_uplift/shipit_uplift/api.yml
src/shipit_uplift/shipit_uplift/coverage_for_file_impl.py

shipit_uplift: Add endpoint for getting coverage for a file at a given changeset

---

lib/cli_common/cli_common/command.py
src/shipit_code_coverage/shipit_code_coverage/codecov.py

Each commit is a different small improvement.
Fixes #715.

cli_common, shipit_code_coverage: Miscellaneous improvements

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

See #736 and #737 for more context.

Miscellaneous improvements for LCOV rewriting

---

src/shipit_uplift/shipit_uplift/api.py
src/shipit_uplift/shipit_uplift/api.yml
src/shipit_uplift/shipit_uplift/coverage_chunks_for_patch_impl.py

This is a PoC and will probably live somewhere else at some point, but for now this is a good place to showcase it.

shipit_uplift: Add prototype API to retrieve chunks given a patch

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/taskcluster.py
src/shipit_code_coverage/tests/test_taskcluster.py

shipit_code_coverage: Wait until test task is finished running before downloading its artifacts

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/utils.py
src/shipit_code_coverage/tests/test_codecov.py

shipit_code_coverage: Generate report of functions with no coverage

---

src/shipit_code_coverage/default.nix
src/shipit_code_coverage/shipit_code_coverage/codecov.py

shipit_code_coverage: Stop rewriting LCOV files

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/taskcluster.py
src/shipit_code_coverage/tests/test_codecov.py
src/shipit_code_coverage/tests/test_taskcluster.py

shipit_code_coverage: Generate chunk to tests mapping

---

src/shipit_static_analysis/shipit_static_analysis/lint.py
src/shipit_static_analysis/tests/test_lint.py
src/shipit_static_analysis/tests/test_reporter_mozreview.py

shipit_static_analysis: Lint entire files rather than modified lines only

---

src/shipit_code_coverage/shipit_code_coverage/notifier.py

shipit_code_coverage: Show commit description in low coverage notifications

---

src/shipit_uplift/requirements.nix
src/shipit_uplift/requirements.txt
src/shipit_uplift/requirements_frozen.txt

shipit_uplift: Remove whatthepatch from the requirements

---

src/shipit_uplift/shipit_uplift/coverage.py
src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py

shipit_uplift: Use .format instead of %

---

src/shipit_uplift/shipit_uplift/coverage.py
src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py

Reverts mozilla-releng/services#864

Revert "shipit_uplift: Use .format instead of %"

---

.github/CODEOWNERS

https://help.github.com/articles/about-codeowners/

adding code owners

---

.github/CODEOWNERS

I always do the same mistake :smile:

Fix Bastien's GitHub handle

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py

shipit_code_coverage: Store strings in chunk mapping file

---

nix/requirements_override.nix
src/shipit_pulse_listener/requirements-dev.txt
src/shipit_pulse_listener/requirements.nix
src/shipit_pulse_listener/requirements_frozen.txt
src/shipit_pulse_listener/shipit_pulse_listener/__init__.py
src/shipit_pulse_listener/shipit_pulse_listener/monitoring.py
src/shipit_pulse_listener/tests/conftest.py
src/shipit_pulse_listener/tests/test_bot.py
src/shipit_pulse_listener/tests/test_monitoring.py

Reduce shipit-pulse-listener notification noise

---

nix/lib/default.nix
src/shipit_code_coverage/default.nix
src/shipit_pulse_listener/shipit_pulse_listener/hook.py
src/shipit_pulse_listener/tests/conftest.py
src/shipit_pulse_listener/tests/test_hook.py
src/shipit_static_analysis/default.nix

Fixes #915.
r? @La0 for the shipit_pulse_listener parts
r? @garbas for the Nix stuff (I bet there's a cleaner way to mkTaskclusterMergeEnv)

 Move 'deadline', 'expires', and 'created' from the hook definition to the task template and use triggerHook method to trigger the hook

---

src/shipit_pulse_listener/shipit_pulse_listener/monitoring.py
src/shipit_pulse_listener/tests/test_monitoring.py

shipit_pulse_listener: Fix spacing between hook reports in monitoring emails

---

nix/lib/default.nix
src/shipit_pulse_listener/shipit_pulse_listener/hook.py
src/shipit_pulse_listener/tests/conftest.py

Follow up to #919. Fixes #930.

Fix triggering hooks from pulse listener

---

src/shipit_uplift/tests/conftest.py

Stop using yield_fixture 

---

src/shipit_uplift/shipit_uplift/api.py

shipit_uplift: Retain changeset coverage results for 2 days instead of 1 day

---

src/releng_docs/index.rst
src/releng_docs/projects/shipit-code-coverage.rst

releng_docs: Explain how to verify shipit-code-coverage after deployment

---

lib/cli_common/cli_common/utils.py
src/shipit_code_coverage/shipit_code_coverage/artifacts.py
src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/report_generators.py

Remove utils.mkdir and use os.makedirs instead

---

lib/backend_common/backend_common/auth0.py
src/shipit_signoff/settings.py
src/shipit_signoff/shipit_signoff/util.py
src/shipit_signoff/tests/conftest.py
src/shipit_workflow/requirements.nix
src/shipit_workflow/requirements.txt
src/shipit_workflow/settings.py
src/shipit_workflow/shipit_workflow/__init__.py
src/shipit_workflow/shipit_workflow/api.py
src/shipit_workflow/shipit_workflow/api.yml
src/shipit_workflow/shipit_workflow/models.py
src/shipit_workflow/shipit_workflow/release.py
src/shipit_workflow/shipit_workflow/tasks.py
src/shipit_workflow/tests/client_secrets.json
src/shipit_workflow/tests/conftest.py
src/shipit_workflow/tests/test_example.py
src/shipit_workflow/tests/test_release.py

This is the initial API that I would like to get some feedback on.

[WIP] shipit-workflow: Initial Ship-it API

---

src/shipit_static_analysis/shipit_static_analysis/report/mozreview.py
src/shipit_static_analysis/shipit_static_analysis/report/phabricator.py
src/shipit_static_analysis/shipit_static_analysis/revisions.py
src/shipit_static_analysis/tests/conftest.py
src/shipit_static_analysis/tests/mocks/mozreview_auth.json
src/shipit_static_analysis/tests/mocks/mozreview_comments_12345_51.json
src/shipit_static_analysis/tests/mocks/mozreview_filediff_12345_2.json
src/shipit_static_analysis/tests/mocks/mozreview_filediff_12345_2_diffdata.json
src/shipit_static_analysis/tests/mocks/mozreview_files_12345.json
src/shipit_static_analysis/tests/mocks/mozreview_reviews_12345.json
src/shipit_static_analysis/tests/mocks/mozreview_root.json
src/shipit_static_analysis/tests/mocks/mozreview_session.json
src/shipit_static_analysis/tests/mocks/mozreview_user.json
src/shipit_static_analysis/tests/mocks/mozreview_user_another.json
src/shipit_static_analysis/tests/test_reporter_mozreview.py

shipit-static-analysis: Run as an idempotent task

---

src/shipit_uplift/shipit_uplift/coverage.py

Removed get_directory_coverage functions from shipit_uplift

---

src/shipit_code_coverage/shipit_code_coverage/report_generators.py
src/shipit_code_coverage/tests/test_report_generators.py

Combine zero coverage files and functions into a single JSON report

---

lib/please_cli/please_cli/config.py

please_cli: add postgresql to the list of the projects

---

src/shipit_code_coverage/shipit_code_coverage/notifier.py

shipit_code_coverage: Misc improvement for low-coverage notifier

---

nix/setup.cfg
src/shipit_uplift/default.nix
src/shipit_uplift/requirements.nix
src/shipit_uplift/requirements_frozen.txt
src/shipit_uplift/tests/fixtures/hgmo_json_revs/8a389e3576db8de5050999777d82aead0a8c62a9.json

shipit_uplift: Switch to Python 3.6

---

nix/lib/default.nix

The scheduler triggers tasks without a payload:
https://docs.taskcluster.net/reference/core/taskcluster-hooks/docs/firing-hooks#scheduled-tasks
The pulse listener triggers them with a payload:
https://docs.taskcluster.net/reference/core/taskcluster-hooks/docs/firing-hooks#triggerhook

shipit_code_coverage: Fix triggering tasks from scheduler

---

src/shipit_code_coverage/default.nix
src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/secrets.py

shipit_code_coverage: Upload the chunk mapping as an artifact and index the coverage task on the TaskCluster index

---

src/shipit_code_coverage/shipit_code_coverage/notifier.py

shipit_code_coverage: Fix exception that the notifier should catch

---

src/shipit_static_analysis/shipit_static_analysis/__init__.py
src/shipit_static_analysis/shipit_static_analysis/clang/format.py
src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py
src/shipit_static_analysis/shipit_static_analysis/cli.py
src/shipit_static_analysis/shipit_static_analysis/config.py
src/shipit_static_analysis/shipit_static_analysis/lint.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py
src/shipit_static_analysis/tests/conftest.py
src/shipit_static_analysis/tests/test_clang.py
src/shipit_static_analysis/tests/test_lint.py
src/shipit_static_analysis/tests/test_reporter_mozreview.py
src/shipit_static_analysis/tests/test_revisions.py

This is a part of the old pull request #861. I'm rebasing and splitting it in several smaller chunks.

shipit_static_analysis: Move repo_dir management in settings

---

src/shipit_workflow/.flake8
src/shipit_workflow/shipit_workflow/api.py
src/shipit_workflow/shipit_workflow/models.py
src/shipit_workflow/shipit_workflow/partners.py
src/shipit_workflow/shipit_workflow/release.py
src/shipit_workflow/shipit_workflow/tasks.py

* Add `in_previous_graph_ids` to control behaviour of some (RC) phases
* Shamelessly steal `partners.py` to handle partner repacks

shipit-workflow: Release deps

---

src/releng_frontend/src/static/trychooser/index.html

They have been missing for a while :(

Add test-verify jobs to trychooser

---

src/shipit_bot_uplift/shipit_bot_uplift/report.py
src/shipit_bot_uplift/tests/conftest.py
src/shipit_bot_uplift/tests/test_bot.py
src/shipit_bot_uplift/tests/test_report.py

shipit_bot_uplift: add impacted branches to report email subject

---

src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py
src/shipit_static_analysis/tests/conftest.py

shipit-static-analysis: Do not parse mach timestamps

---

src/shipit_workflow/shipit_workflow/release.py

I didn't bother to move it to the config.

Enable partner repacks only for 61+

---

src/shipit_code_coverage_backend/shipit_code_coverage_backend/coverage_for_file_impl.py
src/shipit_code_coverage_backend/tests/fixtures/coverage_changeset_by_file.json

shipit_code_coverage_backend: git_build_changeset should be the git changeset corresponding to the hg build changeset

---

src/shipit_workflow/shipit_workflow/models.py

disable partner flag; stop populating release_partner_config

---

lib/please_cli/please_cli/config.py

* Restore shipit-uplift
* Fix releng_frontend #1079

please_cli : Update deployment conf

---

nix/tools/mercurial.nix
src/shipit_code_coverage/default.nix
src/shipit_code_coverage/requirements.txt
src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/report_generators.py
src/shipit_code_coverage/tests/test_report_generators.py

Add file info for uncovered files

---

src/shipit_code_coverage/tests/conftest.py
src/shipit_code_coverage/tests/test_report_generators.py

Move fake_repo stuff to a pytest fixture

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/hgmo.py
src/shipit_code_coverage/shipit_code_coverage/notifier.py
src/shipit_code_coverage/shipit_code_coverage/report_generators.py

shipit_code_coverage: Create a context manager to run a local hgmo server

---

src/shipit_code_coverage/shipit_code_coverage/codecov.py
src/shipit_code_coverage/shipit_code_coverage/report_generators.py
src/shipit_code_coverage/tests/test_report_generators.py

shipit_code_coverage: Add revision in zero_coverage_report

---

src/shipit_static_analysis/shipit_static_analysis/revisions.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py
src/shipit_static_analysis/tests/test_revisions.py

shipit-static-analysis: Use top of MC instead of tip to get common hg ancestor

---

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py
src/shipit_code_coverage/tests/test_taskcluster.py

Fixes #1150.
Depends on #1179.

shipit_code_coverage: Remove fallback on opt build

---

src/shipit_static_analysis/default.nix
src/shipit_static_analysis/shipit_static_analysis/lint.py
src/shipit_static_analysis/shipit_static_analysis/workflow.py

shipit-static-analysis: Upgrade nodejs version to 8.9.4, fixes #1193.

---

lib/please_cli/please_cli/deploy.py

please_cli: trigger a release when deploying to heroku

---

nix/lib/crates.json
src/shipit_code_coverage/default.nix

shipit_code_coverage: update grcov to 0.1.38

---

src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py
src/shipit_static_analysis/tests/conftest.py
src/shipit_static_analysis/tests/mocks/clang-issues.txt
src/shipit_static_analysis/tests/mocks/clang-output.txt
src/shipit_static_analysis/tests/test_clang.py

shipit-static-analysis: Enhance issue body parser, fixes #1251

---

lib/backend_common/backend_common/__init__.py
lib/backend_common/backend_common/auth.py
lib/backend_common/backend_common/auth0.py
lib/backend_common/backend_common/cache.py
lib/backend_common/backend_common/db.py
lib/backend_common/backend_common/dockerflow.py
lib/backend_common/backend_common/pulse.py
lib/please_cli/please_cli/build.py
lib/please_cli/please_cli/config.py
lib/please_cli/please_cli/decision_task.py
nix/lib/default.nix
src/releng_docs/conf.py
src/shipit_workflow/default.nix

See #148 for the details.
@garbas can you provide some feedback for this initial not-yet-tested PR, please.

Dockerflow

---

src/shipit_static_analysis/tests/conftest.py
src/shipit_static_analysis/tests/mocks/clang-repeats.txt
src/shipit_static_analysis/tests/test_clang.py

PR #1276 missed an explicit unit test (the behaviour was tested through before/after tests)

shipit-static-analysis: Add unit test for clang repeated issues

---

src/shipit_code_coverage_backend/shipit_code_coverage_backend/api.yml
src/shipit_code_coverage_backend/shipit_code_coverage_backend/services/active_data.py
src/shipit_code_coverage_backend/shipit_code_coverage_backend/v2/__init__.py
src/shipit_code_coverage_backend/shipit_code_coverage_backend/v2/base.py
src/shipit_code_coverage_backend/shipit_code_coverage_backend/v2/path.py

shipit-code-coverage-backend: Add new endpoint /v2/path

---

lib/please_cli/please_cli/deploy.py

Needed to fix `staticanalysis/frontend` deployment

please_cli: Normalize tmp_dir for S3 upload for sub projects

---

src/shipit_code_coverage/shipit_code_coverage/chunk_mapping.py

closes https://github.com/mozilla/release-services/issues/1337

shipit_code_coverage: Properly ignore awsy and talos in chunk mapping.

---

lib/please_cli/please_cli/config.py

See https://github.com/mozilla-releng/build-cloud-tools/pull/353/files

setup: Update uplift/frontend DNS

---

src/staticanalysis/bot/static_analysis_bot/config.py

staticanalysis/bot: Publish checks by default

---

.github/CODEOWNERS

Update static analysis path in CODEOWNERS

---

lib/cli_common/cli_common/phabricator.py
src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/tests/conftest.py
src/staticanalysis/bot/tests/mocks/phabricator_edge_search.json

Support Phabricator stack of patches 

---

lib/cli_common/cli_common/phabricator.py

Useful when looking for parents diffs

Support missing base revision

---

lib/cli_common/cli_common/phabricator.py
src/codecoverage/backend/tests/conftest.py

cli_common: Add API to upload coverage or linting/static analysis data to Phabricator

---

src/codecoverage/bot/code_coverage_bot/codecov.py

Closes https://github.com/mozilla/release-services/issues/1411
It doesn't look like these directories should be needed anywhere else in the code.

[WIP] codecoverage/bot: Move artifacts and report dirs to a temporary dir

---

src/staticanalysis/bot/static_analysis_bot/__init__.py
src/staticanalysis/bot/static_analysis_bot/clang/__init__.py
src/staticanalysis/bot/static_analysis_bot/clang/tidy.py
src/staticanalysis/bot/static_analysis_bot/cli.py
src/staticanalysis/bot/static_analysis_bot/infer/__init__.py
src/staticanalysis/bot/static_analysis_bot/infer/infer.py
src/staticanalysis/bot/static_analysis_bot/lint.py
src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/static_analysis_bot/workflow.py
src/staticanalysis/bot/tests/test_revisions.py
src/staticanalysis/frontend/src/Tasks.vue
src/staticanalysis/frontend/src/store.js

Fixes #1378 , #1379 
These `error_code` will then be used by `staticanalysis/frontend` to display stats about error sources
Also display phabricator & bugzilla details

staticanalysis: Display custom errors with codes

---

src/staticanalysis/frontend/src/Stats.vue

Please sort by "Published" by default

---

src/shipit/api/shipit_api/__init__.py
src/shipit/api/shipit_api/cli.py

* Include the auth module to init the app properly
* Fix hawk URL

shipit/api: fix /sync endpoint

---

src/shipit/api/shipit_api/api.py

Instad of using releng LDAP group, let's use vpn_cloudops_shipit!

shipit/api: use vpn_cloudops_shipit LDAP group

---

src/codecoverage/bot/code_coverage_bot/artifacts.py

codecoverage/bot: Wait for tasks to be finished before downloading artifacts

---

lib/cli_common/cli_common/phabricator.py
src/shipit_pulse_listener/shipit_pulse_listener/listener.py

Fixes #1510
We can limit the enabled repositories by using TC Secrets (defaults to mozilla-central only)

shipit-pulse-listener: Use common Phabricator API and limit repos

---

nix/gecko_env.nix
src/staticanalysis/bot/default.nix

staticanalysis/bot: Expose gcc libs (missing libstdc++.so.6)

---

lib/please_cli/please_cli/deploy.py

sorry @La0 i tested this locally this time

please_cli: another fix for deploy:S3

---

src/codecoverage/backend/codecoverage_backend/secrets.py
src/codecoverage/backend/codecoverage_backend/services/active_data.py
src/codecoverage/backend/codecoverage_backend/v2/base.py
src/codecoverage/backend/requirements.nix
src/codecoverage/backend/requirements.txt
src/codecoverage/backend/requirements_frozen.txt
src/codecoverage/backend/tests/conftest.py

* HTTP Basic authentication
* Removes esfrontline client
* Based on PR #1566

codecoverage/backend: Support ES read only access

---

src/codecoverage/backend/codecoverage_backend/coverage_by_changeset_impl.py

This is only useful for posterity as documentation.

codecoverage/backend: Improve comments and simplify code of the (old) coverage by changeset API endpoint

---

src/staticanalysis/bot/static_analysis_bot/workflow.py

staticanalysis/bot: Do not stop workflow on improvement patch apply failure

---

src/codecoverage/bot/code_coverage_bot/artifacts.py
src/codecoverage/bot/code_coverage_bot/codecov.py
src/codecoverage/bot/tests/test_artifacts.py

codecoverage/bot: Don't download Talos and AWSY artifacts

---

src/shipit/api/shipit_api/config.py

shipit/api: for project name use full name of the project

---

src/codecoverage/bot/code_coverage_bot/suite_reports.py
src/codecoverage/bot/tests/test_codecov.py
src/codecoverage/bot/tests/test_hgmo.py
src/codecoverage/bot/tests/test_notifier.py
src/codecoverage/bot/tests/test_suite_reports.py

Fix wrong import of cli_common.log

---

src/codecoverage/bot/default.nix
src/codecoverage/bot/tests/conftest.py
src/codecoverage/bot/tests/test_grcov.py

codecoverage/bot: Update grcov to version 0.3.1

---

lib/please_cli/please_cli/config.py
lib/please_cli/please_cli/decision_task.py

add "enable" option to `please_cli/config.py` to be able to disable projects.

WIP: please_cli: Added enable "option" to be able to disable projects (#1513)

---

src/staticanalysis/bot/static_analysis_bot/clang/format.py
src/staticanalysis/bot/static_analysis_bot/clang/tidy.py
src/staticanalysis/bot/static_analysis_bot/infer/infer.py
src/staticanalysis/bot/static_analysis_bot/lint.py
src/staticanalysis/bot/static_analysis_bot/report/phabricator.py
src/staticanalysis/bot/tests/test_reporter_phabricator.py

Part 3/3 of #1271
~~@marco-c This pr is based on #1624, please skip first commit during review.~~

Filter phabricator analyzers to publish (shadow mode)

---

src/staticanalysis/bot/static_analysis_bot/clang/format.py

:sob: 
Will fix [this crash](https://tools.taskcluster.net/groups/ComjN84ARBy7pT36Pla4og/tasks/ComjN84ARBy7pT36Pla4og/runs/0/logs/public%2Flogs%2Flive.log)

Fix dummy leftover bug

---

.taskcluster.yml
lib/please_cli/please_cli/decision_task.py

Notify via IRC when deployment happens

---

src/staticanalysis/bot/default.nix

Add localtime 

---

src/shipit/frontend/src/components/api.js
src/shipit/frontend/src/config.js
src/shipit/frontend/src/configs/master.js
src/shipit/frontend/src/configs/production.js
src/shipit/frontend/src/configs/staging.js
src/shipit/frontend/src/index.js
src/shipit/frontend/src/views/ListReleases/index.js
src/shipit/frontend/src/views/NewRelease/index.js

[ship-it/frontend] Use BACKEND_URL from data-shipit-api-url for accessing backend.

---

lib/please_cli/please_cli/decision_task.py

WIP: please_cli: Notify '#ci' and '#moc' IRC channels that deployment to production is about to start.(#1568)

---

src/shipit/frontend/src/components/api.js
src/shipit/frontend/src/config.js
src/shipit/frontend/src/configs/master.js
src/shipit/frontend/src/configs/production.js
src/shipit/frontend/src/configs/staging.js
src/shipit/frontend/src/index.js
src/shipit/frontend/src/views/ListReleases/index.js
src/shipit/frontend/src/views/NewRelease/index.js

Reverts mozilla/release-services#1636

Revert "[ship-it/frontend] Use BACKEND_URL from data-shipit-api-url for accessing backend."

---

src/staticanalysis/frontend/src/Check.vue
src/staticanalysis/frontend/src/Progress.vue
src/staticanalysis/frontend/src/Stats.vue
src/staticanalysis/frontend/src/mixins.js
src/staticanalysis/frontend/src/store.js

And avoid being limited to 1000 tasks

Load all tasks available

---

src/shipit/api/shipit_api/__init__.py

shipit/api: Fix IRC env var

---

nix/gecko_env.nix

We must update cbindgen to 0.6.7.
Fixes #1662.

Update cbindgen to 0.6.7

---

src/docs/deploy/regular.rst

:warning: The message to #moc & #ci was not sent when releasing on production.

docs: Remove IRC notification

---

src/staticanalysis/bot/requirements.nix
src/staticanalysis/bot/requirements_frozen.txt
src/staticanalysis/bot/tests/test_revisions.py

Fixes #1674 and adds a regression test for it.

staticanalysis/bot: Update parsepatch to latest version and add a regression test for checking if an issue is in a revision

---

nix/default.nix
nix/lib/default.nix
src/docs/default.nix
src/shipit/frontend/default.nix
src/staticanalysis/frontend/default.nix

https://github.com/mozilla/release-services/issues/990

please-cli: display in which project shell you are

---

nix/gecko_env.nix

staticanalysis/bot: Bump rust to 1.30.0

---

src/shipit/frontend/src/configs/testing.js

At this point it is the same as staging.js

shipit/frontent: add testing config

---

src/shipit/frontend/src/views/ListReleases/index.js

Firefox RC has a special case, when we want to skip pushing the updates
to the beta channel and proceed with the release-only phases. In this
case we should be able to push to CDNs without requiring ship_firefox_rc
to be scheduled.

shipit/frontend: make ship_firefox_rc skippable

---

lib/please_cli/please_cli/build.py
lib/please_cli/please_cli/check.py
lib/please_cli/please_cli/config.py

please-cli: change ./please check to use nix-build instead of nix-shell

---

src/staticanalysis/bot/static_analysis_bot/workflow.py

Tentative fix for #1701 (untested).

staticanalysis/bot: Fix #1701, clean up after 'before' analysis.

---

src/staticanalysis/frontend/src/Task.vue
src/staticanalysis/frontend/src/store.js

[This page](https://static-analysis.moz.tools/#/task/I3oLx3McRNqQA25doSoHVA) should list a lot of issue...

staticanalysis/frontend: Fix issues display

---

src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/static_analysis_bot/workflow.py

staticanalysis/bot: Do not use improvement patches from before

---

nix/requirements_override.nix
src/bugbug/data/requirements.nix
src/bugbug/data/requirements.txt
src/bugbug/data/requirements_frozen.txt
src/bugbug/train/requirements.nix
src/bugbug/train/requirements.txt
src/bugbug/train/requirements_frozen.txt

Found a way to get rid of the need to create a symlink in the Spacy package.

bugbug/*: Update requirements

---

lib/cli_common/cli_common/pulse.py
src/shipit/api/shipit_api/worker.py

* worker.cmd method not being called in flask context
* ensure exchange is created before binding to it

shipit/api: worker was not starting this should fix it

---

lib/cli_common/cli_common/command.py
lib/please_cli/default.nix
lib/please_cli/please_cli/update_dependencies.py
lib/please_cli/tests/test_dummy.py
nix/setup.cfg
src/shipit/api/shipit_api/cli.py
src/shipit/api/shipit_api/product_details.py

hide password in git urls which are used when cloning and pushing product details and updated dependencies

generate product details in a subfolder

---

src/shipit/api/shipit_api/config.py

See https://github.com/mozilla-releng/ship-it/pull/250

Bump FIREFOX_NIGHTLY to 67

---

src/tooltool/api/default.nix

tooltool/api: remove redundant workerType specification, fixed #1843

---

src/staticanalysis/bot/static_analysis_bot/workflow.py

The scope of this patch is to have a method to continue the analysis process
even if an analyzer has failed.
In a case of failure, the exception is logged and pushed to Sentry.

staticanalysis/bot: Forward exceptions encountered during analyzer run(...) to Sentry.

---

src/staticanalysis/bot/static_analysis_bot/__init__.py
src/staticanalysis/bot/static_analysis_bot/coverage.py
src/staticanalysis/bot/static_analysis_bot/report/base.py
src/staticanalysis/bot/static_analysis_bot/report/phabricator.py
src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/static_analysis_bot/workflow.py
src/staticanalysis/bot/tests/conftest.py
src/staticanalysis/bot/tests/mocks/zero_coverage_report.json
src/staticanalysis/bot/tests/test_coverage.py
src/staticanalysis/bot/tests/test_lint.py
src/staticanalysis/bot/tests/test_reporter_phabricator.py

staticanalysis/bot: Publish a warning comment when a revision contains files that have zero coverage

---

src/staticanalysis/frontend/src/Check.vue
src/staticanalysis/frontend/src/Task.vue
src/staticanalysis/frontend/src/store.js

Screenshot of current stats on production data: ![Screenshot of current stats](https://i.imgur.com/GSxMjCs.png)

staticanalysis/frontend: Fix coverity bugs in stats, fixes #1887

---

src/staticanalysis/bot/static_analysis_bot/__init__.py
src/staticanalysis/bot/static_analysis_bot/cli.py
src/staticanalysis/bot/static_analysis_bot/config.py
src/staticanalysis/bot/static_analysis_bot/lint.py
src/staticanalysis/bot/static_analysis_bot/workflows/__init__.py
src/staticanalysis/bot/static_analysis_bot/workflows/base.py
src/staticanalysis/bot/static_analysis_bot/workflows/local.py
src/staticanalysis/bot/static_analysis_bot/workflows/remote.py
src/staticanalysis/bot/tests/conftest.py
src/staticanalysis/bot/tests/test_lint.py
src/staticanalysis/bot/tests/test_remote.py

It now works on Taskcluster, after a trigger from push. [Example task](https://tools.taskcluster.net/groups/FjiRyqTxSz2bnSoWyX_sYw/tasks/bSWmtI8zQ5WTGezsLuF8mg/runs/0/logs/public%2Flogs%2Flive.log)

Try analysis ending task

---

src/pulselistener/pulselistener/mercurial.py
src/pulselistener/tests/test_mercurial.py

This is needed to send the phabricator diff information to all the tasks generated on try, and avoid an empty try job warning

pulselistener: Add custom try_task_config.json on push to try

---

src/staticanalysis/bot/static_analysis_bot/lint.py
src/staticanalysis/bot/static_analysis_bot/report/base.py

Add '--warnings' to 'mozlint'

---

.taskcluster.yml
lib/please_cli/please_cli/decision_task.py
src/docs/deploy/regular.rst

This channel has been retired.

Remove #moc from list of channels to notify.

---

src/staticanalysis/bot/default.nix
src/staticanalysis/frontend/src/Choice.vue
src/staticanalysis/frontend/src/Tasks.vue
src/staticanalysis/frontend/src/store.js

This gives me the following stats:

staticanalysis/frontend: Detect killed tasks, fixes #1927

---

src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/tests/test_reporter_debug.py
src/staticanalysis/frontend/src/Tasks.vue

Export Phabricator numerical diff id in Taskcluster payload (#1921)

---

src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/static_analysis_bot/workflows/base.py
src/staticanalysis/bot/tests/conftest.py
src/staticanalysis/bot/tests/test_reporter_debug.py
src/staticanalysis/bot/tests/test_workflow.py

The goal is to display the source on the frontend (try or phabricator)

Track SA tasks from try

---

src/staticanalysis/bot/static_analysis_bot/cli.py
src/staticanalysis/bot/static_analysis_bot/config.py
src/staticanalysis/bot/static_analysis_bot/workflows/local.py

Add a watchdog around mercurial clone

---

src/staticanalysis/bot/static_analysis_bot/clang/format.py
src/staticanalysis/bot/static_analysis_bot/clang/tidy.py
src/staticanalysis/bot/static_analysis_bot/lint.py
src/staticanalysis/bot/static_analysis_bot/task.py
src/staticanalysis/bot/static_analysis_bot/workflows/remote.py
src/staticanalysis/bot/tests/test_clang.py
src/staticanalysis/bot/tests/test_lint.py
src/staticanalysis/bot/tests/test_remote.py
src/staticanalysis/bot/tests/test_reporter_phabricator.py

Nedds to merge #1953 first, then rebase

Support mutiple remote analyzers

---

lib/cli_common/cli_common/phabricator.py
src/codecoverage/bot/code_coverage_bot/phabricator.py
src/staticanalysis/bot/static_analysis_bot/__init__.py
src/staticanalysis/bot/static_analysis_bot/clang/format.py
src/staticanalysis/bot/static_analysis_bot/clang/tidy.py
src/staticanalysis/bot/static_analysis_bot/cli.py
src/staticanalysis/bot/static_analysis_bot/config.py
src/staticanalysis/bot/static_analysis_bot/coverage.py
src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py
src/staticanalysis/bot/static_analysis_bot/infer/infer.py
src/staticanalysis/bot/static_analysis_bot/lint.py
src/staticanalysis/bot/static_analysis_bot/report/phabricator.py
src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/static_analysis_bot/task.py
src/staticanalysis/bot/static_analysis_bot/utils.py
src/staticanalysis/bot/static_analysis_bot/workflows/base.py
src/staticanalysis/bot/static_analysis_bot/workflows/local.py
src/staticanalysis/bot/static_analysis_bot/workflows/remote.py
src/staticanalysis/bot/tests/conftest.py
src/staticanalysis/bot/tests/test_clang.py
src/staticanalysis/bot/tests/test_coverage.py
src/staticanalysis/bot/tests/test_coverity.py
src/staticanalysis/bot/tests/test_issues.py
src/staticanalysis/bot/tests/test_lint.py
src/staticanalysis/bot/tests/test_reporter_phabricator.py
src/staticanalysis/bot/tests/test_revisions.py
src/staticanalysis/bot/tests/test_workflow.py

HarborMaster support

---

src/staticanalysis/bot/static_analysis_bot/__init__.py
src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/tests/test_revisions.py

Fixes #2005.
Will certainly allow for a push to prod.

staticanalysis/bot: Check a path is in revision before publishing in before/after

---

nix/gecko_env.nix

nix: Bump rust-cbindgen to 0.8.3

---

nix/requirements_override.nix
src/bugbug/data/requirements.nix
src/bugbug/data/requirements.txt
src/bugbug/data/requirements_frozen.txt
src/bugbug/eval/requirements.nix
src/bugbug/eval/requirements.txt
src/bugbug/eval/requirements_frozen.txt
src/bugbug/train/requirements.nix
src/bugbug/train/requirements.txt
src/bugbug/train/requirements_frozen.txt

I've updated the dependencies manually.

bugbug/*: Update dependencies

---

src/staticanalysis/bot/default.nix

I manually added it to the staging hook to test it: [it works](https://tools.taskcluster.net/index/project.releng.services.tasks) !

staticanalysis/bot: Add scope for monitoring & restart

---

src/staticanalysis/bot/static_analysis_bot/cli.py
src/staticanalysis/bot/static_analysis_bot/revisions.py

Forgot that behaviour in the last PR :sob:

staticanalysis/bot: Do not update build status when phabricator reporter is disabled

---

src/staticanalysis/bot/static_analysis_bot/workflows/remote.py
src/staticanalysis/bot/tests/test_remote.py

Do not crash when only decision task is in deps

---

lib/cli_common/cli_common/log.py
src/shipit/api/shipit_api/models.py

By default logbook sets the level to NOTSET (0) what makes it log every
log level.

cli_common: set papertrail log level

---

src/docs/index.rst
src/docs/projects/codecoverage-bot.rst
src/docs/projects/staticanalysis-bot.rst
src/docs/projects/staticanalysis-frontend.rst
src/docs/projects/tooltool.rst
src/docs/projects/treestatus.rst
src/docs/projects/uplift-backend.rst

also fixing some build docs typos

docs: adding documentation on how to request/generate taskcluster client credentials for tooltool

---

src/staticanalysis/bot/static_analysis_bot/cli.py
src/staticanalysis/bot/static_analysis_bot/report/phabricator.py
src/staticanalysis/bot/static_analysis_bot/revisions.py
src/staticanalysis/bot/tests/conftest.py
src/staticanalysis/bot/tests/mocks/phabricator_build_search.json
src/staticanalysis/bot/tests/mocks/phabricator_buildable_search.json
src/staticanalysis/bot/tests/mocks/phabricator_send_message.json
src/staticanalysis/bot/tests/mocks/phabricator_target_search.json
src/staticanalysis/bot/tests/test_reporter_debug.py
src/staticanalysis/bot/tests/test_reporter_mail.py
src/staticanalysis/bot/tests/test_reporter_phabricator.py
src/staticanalysis/bot/tests/test_revisions.py
src/staticanalysis/bot/tests/test_workflow.py

Merge PhabricatorRevision into Revision

---

lib/cli_common/cli_common/phabricator.py

Stop loading a phabricator stack once a base revision is available

---

src/codecoverage/bot/code_coverage_bot/artifacts.py
src/codecoverage/bot/code_coverage_bot/cli.py
src/codecoverage/bot/code_coverage_bot/codecov.py

codecoverage/bot: Filter tasks from CLI

---

src/staticanalysis/bot/static_analysis_bot/report/base.py
src/staticanalysis/bot/tests/test_reporter_phabricator.py

staticanalysis/bot: Fix phrasing.

---

src/pulselistener/pulselistener/hook.py
src/pulselistener/pulselistener/listener.py
src/pulselistener/pulselistener/phabricator.py
src/pulselistener/pulselistener/web.py

Use dedicated process for webserver

---

src/codecoverage/backend/codecoverage_backend/api.yml
src/codecoverage/backend/codecoverage_backend/covdir.py
src/codecoverage/backend/codecoverage_backend/services/gcp.py
src/codecoverage/backend/codecoverage_backend/v2/__init__.py
src/codecoverage/backend/tests/conftest.py
src/codecoverage/backend/tests/test_covdir.py
src/codecoverage/backend/tests/test_gcp.py

codecoverage/backend: Serve history with overall coverage

---

nix/lib/default.nix
src/mapper/api/default.nix

hopefully this fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1483298

mapper/api: increase the gunicorn timeout

---

src/codecoverage/bot/tools/covdir_gen.py

This allows us to create generation task for past data either:
1. for each ingestion
2. once per day
2. once per week
I also added a `--dry-run` mode to safely test it.
Another small detail: the task name now has the date before the hash, so they are ordered by date in the taskcluster interface

Add option to trigger one generation per week

---

src/codecoverage/bot/code_coverage_bot/uploader.py

Ingest new report on associated backend

---

src/shipit/api/shipit_api/config.py
src/shipit/api/shipit_api/tasks.py

I noticed I can't trigger RC builds on Fennec, anymore.
r? @rail 
Follows #2056 up

Bug 1559115 - Allow firefox_release_rc flavors

---

src/shipit/api/settings.py

Bug 1559115: part 3 - Give the scope to run ship_fennec_release_rc

---

src/shipit/api/requirements.nix
src/shipit/api/requirements_frozen.txt

I'm unsure if I dealt with requirements correctly. r? @garbas

Bug 1561617 - Bump mozilla-version to 0.3.3

---

src/codecoverage/bot/tests/test__system.py

Add system check for robustcheckout & genhtml

---

lib/please_cli/please_cli/config.py

codecoverage: Stop deployments.

---

src/pulselistener/pulselistener/__init__.py
src/pulselistener/pulselistener/cli.py
src/pulselistener/pulselistener/hook.py
src/pulselistener/pulselistener/lib/log.py
src/pulselistener/pulselistener/lib/pulse.py
src/pulselistener/pulselistener/lib/taskcluster.py
src/pulselistener/pulselistener/lib/utils.py
src/pulselistener/pulselistener/listener.py
src/pulselistener/pulselistener/mercurial.py
src/pulselistener/pulselistener/monitoring.py
src/pulselistener/pulselistener/phabricator.py
src/pulselistener/pulselistener/web.py
src/pulselistener/requirements.txt
src/pulselistener/tests/conftest.py
src/pulselistener/tests/test_code_coverage_listener.py
src/pulselistener/tests/test_hook.py

First step toward lib split
Oversedes #2193

Remove cli_common usage from pulselistener

---

lib/please_cli/please_cli/config.py

Refs https://github.com/mozilla/release-mgmt-projects/issues/226

setup: Disable pulselistener on staging.

---

src/pulselistener/pulselistener/hook.py
src/pulselistener/pulselistener/lib/bus.py
src/pulselistener/pulselistener/lib/web.py
src/pulselistener/pulselistener/listener.py
src/pulselistener/tests/test_bus.py
src/pulselistener/tests/test_code_coverage_listener.py
src/pulselistener/tests/test_hook.py
src/pulselistener/tests/test_phabricator_listener.py

Add message bus & use it for webserver communication

---

src/pulselistener/pulselistener/lib/bus.py
src/pulselistener/pulselistener/listener.py
src/pulselistener/tests/test_bus.py

No more `is_full`, nor `nb_messages`

Use Queues maxsize to limit execution.

---

src/pulselistener/pulselistener/config.py
src/pulselistener/pulselistener/hook.py
src/pulselistener/pulselistener/lib/monitoring.py
src/pulselistener/pulselistener/listener.py
src/pulselistener/tests/test_hook.py
src/pulselistener/tests/test_monitoring.py

Convert monitoring to message bus

---

src/pulselistener/pulselistener/lib/mercurial.py

Backport from https://github.com/mozilla/bugbug/pull/866

Load needed patches in stack only

---

src/shipit/api/shipit_api/api.py
src/shipit/api/shipit_api/models.py
src/shipit/api/shipit_api/product_details.py
src/shipit/api/shipit_api/release.py
src/shipit/api/tests/test_release.py

Centralize version parsing in mozilla-version 0.4.x

---

src/shipit/api/shipit_api/config.py

Per https://docs.google.com/spreadsheets/d/1SCFDvnKGHSd7BvAvIAXA135IQnp0W4Mik9Y-jgImaJ8/edit#gid=1793473785

Update timeline for next merge and release
