mozilla/release-services

.gitignore, Makefile, src/shipit_dashboard/README.md, src/shipit_dashboard/bootstrap.sh, src/shipit_dashboard/shipit_dashboard/__init__.py, src/shipit_dashboard/shipit_dashboard/api.py, src/shipit_dashboard/shipit_dashboard/swagger.yml, src/shipit_dashboard/shipit_dashboard/workflow.py, src/shipit_frontend/elm-package.json, src/shipit_frontend/elm-package.nix, src/shipit_frontend/node-packages.nix, src/shipit_frontend/package.json, src/shipit_frontend/src/App.elm, src/shipit_frontend/src/App/ReleaseDashboard.elm, src/shipit_frontend/src/App/User.elm, src/shipit_frontend/src/index.js
This PR adds several features for the shipit dashboard:
* Several analysis, with dynamic links in the top bar
* Load initial localstorage user through the port, not the flags, for a unified Msg integration
* Uses the hawk Js library to build the HAWK protocol header, and send it to the backend for each request
* Generic method to send requests towards the backend, always using the hawk header
* some cosmetic changes (buttons, keywords, ...)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/garbas/mozilla-releng/48)
=> Shipit: multiple analysis, HAWK port

src/shipit_dashboard/shipit_dashboard/api.py, src/shipit_frontend/src/App.elm, src/shipit_frontend/src/App/Hawk.elm, src/shipit_frontend/src/App/ReleaseDashboard.elm, src/shipit_frontend/src/App/User.elm, src/shipit_frontend/src/index.js
A new module "Hawk" in the elm code permits to build a new HAWK request every time.
It works with the current implementation of the backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/garbas/mozilla-releng/54)
=> Shipit: Generic hawk requests

Makefile, src/shipit_frontend/src/index.js
This patch adds a step after building a js app in the makefile, in order to configure the backend (or any other setting in the bundle).
Any variable set in `APP_STAGING_ENV_appname` or `APP_PRODUCTION_ENV_appname` will be replaced directly in the bundle before deployment
=> Configure js apps with backend url before S3 deploy.

Makefile
This patch removes some bashism that didn't work in dash ([[, source)
and requires Nix to be installed before running anything. If Nix is not
install the `nix` target installs it, tries to source environment
variables, but they are not available in other targets.
=> Require Nix, kill bashism

src/releng_clobberer/releng_clobberer/__init__.py, src/releng_clobberer/releng_clobberer/api.yml, src/releng_tooltool/releng_tooltool/__init__.py, src/releng_tooltool/releng_tooltool/api.yml, src/shipit_dashboard/shipit_dashboard/__init__.py, src/shipit_dashboard/shipit_dashboard/api.yml
motivation behind this is that in longer term swagger (the name) is going to be replaced by OpenApi ... we can just use the correct name. i have also seen other projects using ``api.yml`` so it is kind of non-written convention.
i've also added constrains that this are only json api endpoints
=> renaming swagger.yml to api.yml

Makefile, src/shipit_dashboard/settings.py
=> Shipit dashboard: use postgres:// prefix instead of postgresql://

src/releng_frontend/src/trychooser/index.html
Based on #132 I threw together a patch to fix bug 1325719.
cc @ehsan
=> Bug 1325719 - Add win32/win64-st-an build options to trychooser

.taskcluster.yml, Makefile, src/releng_docs/services_shipit.rst, src/shipit_bot_uplift/default.nix, src/shipit_bot_uplift/requirements_override.nix, src/shipit_bot_uplift/shipit_bot_uplift/mercurial.py, src/shipit_bot_uplift/shipit_bot_uplift/sync.py, src/shipit_dashboard/default.nix, src/shipit_dashboard/requirements.txt, src/shipit_dashboard/requirements_frozen.txt, src/shipit_dashboard/requirements_generated.nix, src/shipit_dashboard/setup.py
As recommended by Gregory Szorc, i simplified the mercurial branch checkout process by using the Mozilla extension [robustcheckout](https://hg.mozilla.org/hgcustom/version-control-tools/file/tip/hgext/robustcheckout/__init__.py)
=> shipit_bot_uplift: Use robust checkout

src/releng_frontend/src/static/trychooser/index.html
This is generating unnecessary traffic on Try when people just click all the things.
=> Move 10.6 and XP into a legacy group so people stop selecting them

src/releng_frontend/src/static/trychooser/index.html
This PR is trying to fix [Bug 1347096](https://bugzilla.mozilla.org/show_bug.cgi?id=1347096) because we support the linux64-stylo T-push / π-push already from [Bug 1340911](https://bugzilla.mozilla.org/show_bug.cgi?id=1340911).
e.g. `try: -b do -p all -u all[linux64-stylo] -t none`  This will only push tests on linux64-stylo.
Already verified in https://treeherder.mozilla.org/#/jobs?repo=try&revision=0cc5c32cae1451b87adc8d31529d66666b3aba7d
=> releng_frontend: add linux64-stylo into restrict tests to platforms

src/releng_docs/services_shipit.rst
A few of us met yesterday to talk about what the required HTTP API that step services need to implement would be. This is an attempt to start documenting it. I don't think we've fully decided what it will look like, but this is a start.
Here's a dump from the notes we took yesterday, with some open questions:
* Resource based (supports CRUD operations)
* https://github.com/lundjordan/services/blob/shipit-taskcluster/src/shipit_taskcluster/shipit_taskcluster/api.yml
* All steps support a base interface, some steps may have step-specific interfaces
* need to be careful about allowing step status to be overridden, otherwise we may violate signoff requirements
* pipeline will not be changing step status
* may need additional information returned with some statuses (eg: required/completed …
=> Add first pass on step services API docs

src/releng_frontend/src/static/trychooser/trychooser.js
This is a fix for [bug 1354279](https://bugzilla.mozilla.org/show_bug.cgi?id=1354279)
It's only a flag rename, required to mirror the [BE implementation](https://dxr.mozilla.org/mozilla-central/rev/ec8d1d3db50c85037e8077c32c8403570a5df493/testing/mozharness/mozharness/mozilla/testing/talos.py#175).
=> bug 1354279 - update try syntax, for Gecko profiling

src/releng_docs/run.py, src/releng_docs/services_shipit.rst, src/releng_docs/shipit_signoffs, src/shipit_signoff/docs/shipit-signoffs.rst
Now that we've more or less settled on an architecture and policy format, we should add some docs. This could use a bit more fleshing out but it's a start.
@srfraser - could you review this from the Signoffs Service angle?
@garbas - I've incorporated the "put the docs with the app" ideas from #230 - came you let me know what you think about that?
=> Add rudimentary docs for the signoffs service

lib/cli_common/cli_common/taskcluster.py, src/shipit_pulse_listener/requirements.nix, src/shipit_pulse_listener/requirements.txt, src/shipit_pulse_listener/requirements_frozen.txt, src/shipit_pulse_listener/shipit_pulse_listener/__init__.py, src/shipit_pulse_listener/shipit_pulse_listener/cli.py, src/shipit_pulse_listener/shipit_pulse_listener/listener.py
Static analysis and risk assessment tasks must be triggered by some pulse messages.
As Taskcluster does not yet support this behavior, a reccurent task needs to listen to pulse message and triggers tasks.
As Taskcluster does not yet support to modify the environment or command from a hook, we need to read the hook definition, and use the task payload to create a new task.
=> Pulse listener task

nix/lib/default.nix, nix/requirements_override.nix, nix/setup.cfg, src/releng_archiver/setup.cfg, src/releng_clobberer/setup.cfg, src/releng_docs/setup.cfg, src/releng_mapper/setup.cfg, src/releng_tooltool/setup.cfg, src/releng_treestatus/setup.cfg, src/shipit_bot_uplift/setup.cfg, src/shipit_code_coverage/setup.cfg, src/shipit_pipeline/.flake8, src/shipit_pipeline/setup.cfg, src/shipit_pulse_listener/setup.cfg, src/shipit_risk_assessment/setup.cfg, src/shipit_signoff/default.nix, src/shipit_signoff/setup.cfg, src/shipit_static_analysis/setup.cfg, src/shipit_taskcluster/setup.cfg, src/shipit_uplift/setup.cfg
Following up on the last IRC comments, we may want to be consistent with the other projects in release engineering. The following projects use either 159 or 160 characters:
* https://dxr.mozilla.org/build-central/rev/f16d6d84ce68be7a4cf1ee8d0b58d3ebf6b87522/buildbot-configs/tox.ini#51
* https://dxr.mozilla.org/build-central/rev/81124f4c497759ef11d96448b9bd1ab063164e9d/tools/tox.ini#43
* https://dxr.mozilla.org/build-central/rev/f608764128705acea53ff8c6a42482f09038c6b2/cloud-tools/tox.ini#26
* https://github.com/mozilla-releng/funsize/blob/6c78431780545ee8d82529ab324489d2ae266933/tox.ini#L25
* https://github.com/mozilla-releng/scriptworker/blob/e244cd34fe9fbf34dc7d244014217057fcc4b2d7/tox.ini#L41
* https://github.com/mozilla-releng/beetmoverscript/blob/1f043f2c0cba10e7b5668404aac9b6194786ce …
=> flake8: Change max line length to 159

src/releng_frontend/src/static/trychooser/index.html
Example failure: https://treeherder.mozilla.org/logviewer.html#?job_id=93804902&repo=try&lineNumber=662
cc: @garbas
=> Removed windows clang builds, which don't appear to work

src/releng_frontend/src/static/trychooser/index.html
Over the course of a year, we slowly platform-by-platform replaced the mochitest-other suite with separate suites of the things it ran, mochitest-a11y and mochitest-chrome, without ever bothering to update trychooser. Now we've split it up on every platform, and mochitest-o/mochitest-other no longer exists, still without ever bothering to update trychooser.
Having this actually work on every platform depends on a patch for [bug 1357701](https://bugzilla.mozilla.org/show_bug.cgi?id=1357701#c2), but that doesn't actually block this landing, since mochitest-o no longer exists, mochitest-a11y works, and mochitest-chrome works on Linux and Android (and Mac debug, though it working there is only because of yet another bug). 
Having these in there is better than the current state, and having a …
=> Replace mochitest-o with mochitest-a11y and mochitest-chrome

src/releng_frontend/src/static/trychooser/index.html
If there's one thing that's true about trychooser/try syntax, it's that there's no one true thing about it.
Despite the fact that I'll shortly have a PR that adds more individual chunks for mochitests, it doesn't make sense to maintain a list of chunks for reftests: they run in a bewildering variety of chunks (8 on Linux, 1 on Mac and Windows opt, 2 on Windows debug, and only the 2 e10s on Mac debug, and insane 16 and 48 chunks on Android, which I'm not yet prepared to touch), and unlike mochitests where it might be reasonable to run only M10 because you're working on toolkit/components/alerts/ on Linux64 and don't need to run totally unrelated browser/components/feeds/ tests in M1, with reftests you're generally working on... layout stuff, and you need to run the reftest chunks that deal …
=> Fix inaccurate info in reftest/crashtest labels, give up on chunks

src/releng_frontend/src/static/trychooser/index.html
As I rambled on about [separately](https://github.com/mozilla-releng/services/pull/287) for reftests, selecting chunks in trychooser isn't great, but for mochitests it's a simpler "there's 10 chunks on Linux, 5 on Mac and Windows" and [bug 1359213](https://bugzilla.mozilla.org/show_bug.cgi?id=1359213) says there's demand for selecting individual chunks beyond 5.
=> Add mochitest chunks 6-10

src/shipit_pulse_listener/shipit_pulse_listener/listener.py
We want to verify that the commits to be analyzed are actually aimed at the
Firefox repository and not a different one. The correct payload key to check for
that is `repository_url`[0].
[0] https://mozilla-version-control-tools.readthedocs.io/en/latest/mozreview/notifications.html#mozreview-commits-published
=> shipit_pulse_listener: Fix repository URL in static analysis hook.

src/shipit_code_coverage/default.nix, src/shipit_code_coverage/shipit_code_coverage/cli.py, src/shipit_code_coverage/shipit_code_coverage/codecov.py
Fixes #296.
The best way to review these changes is by ignoring whitespace changes: https://github.com/mozilla-releng/services/pull/298/files?w=1.
=> shipit_code_coverage: Cache mozilla-central repository

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/uploader.py, src/shipit_code_coverage/shipit_code_coverage/utils.py
If the task happens to be trigger right after a linux64-ccov build is finished, the commit might be missing on gecko-dev. We need to wait until it's available before proceeding.
=> shipit_code_coverage: Retrieve GitHub commit as late as possible and wait until the mapper is ready

src/shipit_risk_assessment/requirements.txt
Required to fix `project-releng/services-staging-shipit-risk-assessment-bot`
=> shipit_risk_assessment: Fix requirements to load mocoda.

nix/setup.sh
* Quoting for variable expansion to avoid surprises
* Commands running in `if` directly
* Remove unnecessary sudo use for getent and id
* More quote-safe 'cat into file using sudo' approach
=> Safety and compatibility updates for nix/setup.sh

src/releng_docs/index.rst
dash doesn't have the function builtin, causing errors here.
=> Debian derivatives have /bin/sh as dash

nix/lib/crates.json, nix/lib/rust.nix, src/shipit_code_coverage/default.nix, src/shipit_code_coverage/rust.nix
This version of grcov contains some performance improvements.
There's another performance improvement that is available when compiling with the nightly version of Rust, but I will enable it in a separate pull request.
=> shipit_code_coverage: Update grcov to version 0.1.16

please
Macs appear to have an issue with their host:volume mounts using osxfs, and extended attribute permissions, meaning the nix store becomes unreadable during setup if using `cp` to populate it.
Change to use a docker volume rather than a host directory.
If the named volume is empty, and the mount point is not, the mount point's contents are copied into the new volume before the mount occurs. This gives us the same behaviour as the host directory version, but using a named volume. It does make it less easy to modify `/nix/store` when outside a container, but does enable people to run macs.
=> please_cli: Change volume use to enable Mac use

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/uploader.py, src/shipit_code_coverage/shipit_code_coverage/utils.py
The `check_coveralls_job` function is returning `True` when the build is injested and `False` when it isn't. The `wait_until` function was checking for the return value to be not `None`. This meant that, even when the build was not injested and `check_coveralls_job` returned False, `wait_until` was completing.
With this change, we are actually waiting coveralls to injest the build before generating the coverage by dir report.
I've removed the code which raised an exception when Coveralls fails to injest a report, as it's too likely to happen for now.
=> shipit_code_coverage: Fix bug that prevented us from actually waiting for coveralls to injest data

src/shipit_pulse_listener/shipit_pulse_listener/listener.py, src/shipit_static_analysis/default.nix, src/shipit_static_analysis/shipit_static_analysis/cli.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py
This change processes the clang-tidy output to extract potentially detected code problems in order to generate a review (as an email report first, and soon a proper drive-by review on MozReview).
=> shipit_static_analysis: Parse clang-tidy output to extract detected code problems.

src/releng_frontend/src/static/trychooser/index.html, src/releng_frontend/src/static/trychooser/trychooser.js
This PR:
- Adds Windows 10 to the list of available test platforms.
- Stops including platform restrictions when 'none' is chosen ([Bug 1276393](https://bugzilla.mozilla.org/show_bug.cgi?id=1276393))
- Escapes spaces on the example ./mach command ([Bug 1243709](https://bugzilla.mozilla.org/show_bug.cgi?id=1243709))
=> Improve various aspects of trychooser around plaform selection for tests.

src/shipit_taskcluster/shipit_taskcluster/api.py, src/shipit_taskcluster/shipit_taskcluster/api.yml, src/shipit_taskcluster/shipit_taskcluster/models.py, src/shipit_taskcluster/shipit_taskcluster/taskcluster_utils.py
before this bitrots, let's get this into production.
next steps after this lands:
* auth support
* rip out common step logic into backend_common/shipit_steps or something.
@garbas @nthomas-mozilla what do you think?
=> shipit_tasklcuster: initial MVP

src/shipit_static_analysis/shipit_static_analysis/workflow.py
This change tentatively enables the following clang-tidy checkers:
- `clang-analyzer-deadcode.DeadStores`: to report dead / unreachable code
- `readability-else-after-return`: to suggest simplifying things like `if (...) { return nullptr; } else { ... }` to `if (...) ' return nullptr; } ...` (no `else` needed)
It also enables checkers that are prefixed with `mozilla-`, however upstream `clang-tidy` doesn't have any (so enabling `mozilla-*` acivates 0 additional checkers). I'm simply adding this rule so that when we switch to a Mozilla-specific checkers, its own `mozilla-*` rules will already be enabled.
=> shipit_static_analysis: Enable clang-tidy checkers for dead code, else-after-return and mozilla-*

src/shipit_static_analysis/shipit_static_analysis/workflow.py
As mentioned in #373, the generated markdown in static analysis email reports is slightly broken.
In this pull request, I attempt to improve it. I'm not too confident with Python, but the result should look something like this:
**Message**: converting integer literal to bool, use bool literal instead [modernize-use-bool-literals]
**Location**: accessible/atk/AccessibleWrap.cpp:139:3
```
uint32_t* hdr = reinterpret_cast<uint32_t*>(start);
^
auto
```
**Note**: obj-x86_64-pc-linux-gnu/dist/include/nsDebug.h:105:67
**Message**: expanded from macro 'NS_ASSERTION'
```
NS_ASSERTION(0)
^
false
```
(Note: The contents of my example don't make any sense, please pay only attention to the form.)
=> shipit_static_analysis: Improve markdown export for code issues (#373).

src/shipit_static_analysis/shipit_static_analysis/workflow.py
modernize-use-bool-literals is not obvious for now. Add others which works
=> Update the list of checkers for the static analyzers

src/releng_frontend/src/static/trychooser/index.html
Since landed bug 1366404, we add android-aarch64 to treeherder.  So we should add this to trychooser too.
cc: @darchons
=> Add android-aarch64 to trychooser

src/shipit_static_analysis/default.nix, src/shipit_static_analysis/shipit_static_analysis/clang.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py
We no longer need `run-clang-tidy.py` as it's just a wrapper around clang-tidy. This way we control more precisely the options given to clang-tidy and have no longer parsing issues due to mixed thread outputs (each thread build its own issues list).
The optimal number of workers (ie. number of processors is automatically detected)
=> shipit_static_analysis: Multi threads directly in bot

src/releng_frontend/src/static/trychooser/index.html
I've just added a wiki doc about tagging, so this adds it to the try server. Also I've moved the PGO builds link as it makes more sense in the build section.
=> Add a link to information about tagging and improve the location of the PGO builds link.

src/shipit_static_analysis/shipit_static_analysis/clang.py
This turned out to be a pretty quick fix.
However, our regex is becoming convoluted, and I'm wondering if we shouldn't use something simpler like:
```regex
^(.+):(\d+):(\d+): (warning|error|note): ([^\[\]\n]+)(?: \[([\.\w-]+)\])?\n
```
(basically, the description can be anything in a given line except `[` or `]`).
=> shipit_static_analysis: Fix #412 by making clang-tidy regex accept messages including characters '()='.

src/shipit_signoff/tests/conftest.py, src/shipit_signoff/tests/test_flask.py
I noticed this while starting to hack on Balrog signoffs -- when I added a test that verified that we could add a Balrog step, it failed because the UID already existed in the system (because a different test added it).
=> shipit_signoffs: Change fixture scope to function to avoid cross-contamination between different tests.

src/shipit_code_coverage/shipit_code_coverage/cli.py, src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Use REVISION passed as argument if available, otherwise use latest linux64-ccov task.

src/shipit_pulse_listener/shipit_pulse_listener/__init__.py, src/shipit_pulse_listener/shipit_pulse_listener/cli.py, src/shipit_pulse_listener/shipit_pulse_listener/hook.py, src/shipit_pulse_listener/shipit_pulse_listener/listener.py, src/shipit_pulse_listener/shipit_pulse_listener/monitoring.py
This patch adds a monitoring class that provides an async process listening to an async queue.
Other processes (one per hook linked to a pulse message) can then "push" the created task ids into the monitoring queue.
When a task status evolves to complete or failed, the task is removed from the queue and is added to a future mail report.
Mail reports are sent to admins (emails from TC secret) every hour.
=> shipit_pulse_listener: Add tasks monitoring

src/shipit_static_analysis/shipit_static_analysis/workflow.py
Because using it systematically is controversial: https://bugzilla.mozilla.org/show_bug.cgi?id=1371052
=> shipit_static_analysis: Disable 'modernize-use-auto' clang-tidy checker.

nix/default.nix, nix/gecko_env.nix, nix/nixpkgs.json, nix/requirements_override.nix
I'm using the latest revision of nixpkgs-unstable, as Nix pkgs for 17.03 do not have rust 1.17
=> nix: Update nixpkgs to get latest rust 1.17

src/shipit_signoff/shipit_signoff/balrog.py
Found this bug after testing against a local Balrog instance. We need to grab info from the correct endpoint, and parse it correctly! With this fixed, I was able to simulate an end to end Balrog signoff, with:
Creating the step:
```
➜  shipit_signoff git:(local-auth) ✗ curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: Bearer releng1' -d '{"parameters": {},
"policy": {
"method": "balrog",
"definition":
{"sc_id": 2, "object": "rules"}
},
"uid": "2"
}' 'http://localhost:5000/step/2'
{}
```
...which ended up making a request to /api/scheduled_changes/rules?all=1 on Balrog.
Then:
```
➜  shipit_signoff git:(local-auth) ✗ curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer releng1' …
```
=> shipit_signoff: Parse scheduled change information correctly.

src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Ignore talos suites as they aren't exactly tests

src/shipit_code_coverage/shipit_code_coverage/codecov.py
I'm hoping this will fix #481.
`ssh-add` was asking me for a passphrase even though the key doesn't have any, but I've tested again today and it isn't anymore. I'm not sure what was wrong yesterday, but I'm pretty sure not asking for a passphrase is what it is supposed to do.
=> shipit_code_coverage: Use ssh-add to add the deploy key

src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Set self.revision also when the revision is passed as a parameter

src/shipit_code_coverage/default.nix, src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Directly parse grcov results from test machines instead of re-parsing the gcno/gcda files

src/shipit_code_coverage/shipit_code_coverage/codecov.py
Fixes #491.
Need https://bugzilla.mozilla.org/show_bug.cgi?id=1379955 to land first before merging this.
=> shipit_code_coverage: Fail if lcov rewriting fails

src/shipit_code_coverage/default.nix
The new version contains a really small change in the way we map symbolic links in the obj directory to files in the mozilla-central repository.
This change was needed because the mapping file format was updated in https://bugzilla.mozilla.org/show_bug.cgi?id=1378533.
=> shipit_code_coverage: Update grcov to version 0.1.25

src/shipit_frontend/src/App/CodeCoverage.elm, src/shipit_frontend/src/scss/index.scss
=> shipit_frontend: Remove bullets and padding from list of bugs in the coverage by directory report

src/shipit_frontend/src/App/CodeCoverage.elm, src/shipit_uplift/shipit_uplift/api.py, src/shipit_uplift/shipit_uplift/api.yml, src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py
Fixes #508.
For now there's no caching. I'm not expecting many people to look at the same directories of the report on the same day (except maybe the root directory, but it isn't worth it since it would be invalidated every few hours).
=> shipit_uplift, shipit_frontend: Load one directory at a time instead of generating a huge report

lib/please_cli/please_cli/config.py, lib/please_cli/please_cli/decision_task.py, lib/please_cli/please_cli/deploy.py, nix/lib/default.nix
This allows `shipit-pulse-listener` to run on an Heroku worker dyno:
* supports Heroku worker dyno deployment
* build /etc with a file so that network is running fine in Heroku (weird bug)
Fixes #401 & #512
=> Heroku fix for mkPython based projects

src/shipit_static_analysis/shipit_static_analysis/clang.py
Right now the shipit_static_analysis cannot run in Taskcluster tasks since it tries to load an artifact through mach and fails to solve the domain name used (http://taskcluster).
Mach [automatically detects that it's executed in a taskcluster task](https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/taskgraph/optimize.py#l175) env by checking if `TASK_ID` environment variable is set. 
So this quick fix simply unsets in the Python env this variable...
@garbas The root cause seems to be a Nix issue. We already had to [hack the domain name resolution](https://github.com/mozilla-releng/services/blob/master/lib/cli_common/cli_common/taskcluster.py#L64) for taskcluster proxy for our own api clients.
This network resolution issue may also be the root cause of #401, i'd like to have your …
=> shipit_static_analysis: Skip taskcluster proxy usage when loading artifacts through mach

src/shipit_static_analysis/shipit_static_analysis/workflow.py
We noticed many false positives on `MOZ_IMPLICIT` macros, and realized that `MOZ_CLANG_PLUGIN` was not defined (causing the `mozilla-*` checkers to complain about many macros that were accidentally configured for release builds).
Adding the `./mach configure` parameter `--enable-clang-plugin` fixed these issues for me locally.
=> shipit_static_analysis: Configure gecko build with --enable-clang-plugin to fix many false positives.

src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py
Fixes #529 .
Codecov.io is considering **2bc71dbfe39fb68a827b26ec9f0387dfdf6a6030** to be associated with failing CI, its previous (**1b05f8ad37c2b68fdf3ac3dc1265939dce84587e**) with failing CI, then **0c215343b047edda15e96a28ef889afa3d4ecc02** with successful CI (see https://codecov.io/gh/marco-c/gecko-dev).
It is returning wrong information for "1b05f8ad37c2b68fdf3ac3dc1265939dce84587e", probably because of the failing CI thing (even though the CI didn't fail, I'm not sure yet why codecov thinks it did).
From the API's response (https://codecov.io/api/gh/marco-c/gecko-dev), instead of using `commits[0]['commitid']` as the latest and `commits[1]['commitid']` as the previous, we can use `commit['commitid']` as the latest and `commit['parent']` as the previous, as the 'parent' skips …
=> shipit_uplift: Don't use reports associated with commits where codecov.io thinks the CI failed 

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/taskcluster.py, src/shipit_code_coverage/shipit_code_coverage/utils.py
The changes in this PR make the download of coverage artifacts happen in parallel with the cloning/ building of mozilla-central and with the rewriting of JSVM artifacts.
The uploads to coveralls and codecov are parallelized too.
I expect most of the speedup will come from the parallelization of the download of coverage artifacts (a I/O-bound operation with basically almost 0% CPU utilization that takes around 15 minutes in total) with the rewriting of the JSVM artifacts (a CPU-bound operation).
=> shipit_code_coverage: Parallelize shipit-code-coverage task more

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/utils.py
```
cli_common.command: Command failed with code: 128 (output=b'' command='git clone https://github.com/marco-c/gecko-dev' error=b"Cloning into 'gecko-dev'...\nerror: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 110\nfatal: The remote end hung up unexpectedly\nfatal: early EOF\nfatal: index-pack failed\n")
Error: Command (`git clone https://github.com/marco-c/gecko-dev`) failed with code: 128.
```
Updating the GitHub repository periodically fails, so let's ignore failures here.
=> shipit_code_coverage: Don't fail the task when pushing to GitHub fails

src/shipit_code_coverage/shipit_code_coverage/codecov.py
I'm seeing rewrite_jsvm_lcov being called with artifacts with which it shouldn't be called (e.g. artifacts whose name doesn't contain `code-coverage-jsvm.zip`). I think it's a scope issue.
=> shipit_code_coverage: Fix scope issue that caused rewrite_jsvm_lcov to be called with random artifacts

src/releng_treestatus/releng_treestatus/api.py, src/releng_treestatus/releng_treestatus/api.yml
fixes MOZILLA-RELENG-SERVICES-8R1 and MOZILLA-RELENG-SERVICES-8R2 on sentry
=> releng_treestatus: format in query was used in old old v0 api

src/releng_frontend/src/Main.elm
NagBot front end currently hangs when a user is not logged in, this PR stops any action from taking place without a login and displays an error message telling the user they must log in.
=> releng-frontend: Fix hang error when no user logged in

src/shipit_code_coverage/shipit_code_coverage/codecov.py
This is actually an optional parameter and is currently causing problems since we have multiple builds per day.
=> shipit_code_coverage: Remove service-number grcov's parameter

src/releng_treestatus/releng_treestatus/api.py, src/shipit_pipeline/shipit_pipeline/api.py, src/shipit_static_analysis/shipit_static_analysis/cli.py, src/shipit_taskcluster/shipit_taskcluster/api.py, src/shipit_taskcluster/shipit_taskcluster/taskcluster_utils.py
Some of the logging is still being done by Python's ```logging``` module. This PR ensures all logging is done via the ```cli_common.log``` module.
=> Ensure all logging uses cli_common utility

lib/backend_common/backend_common/notifications.py, src/releng_notification_policy/releng_notification_policy/api.py, src/releng_notification_policy/settings.py
Adds a method in backend_common for other services to create nagbot messages (pipeline, signoff etc).
Two thoughts:
1. I added a method to generate random UID, should I remove and just assume caller will always provide?
2. Should this be implemented as a backend_common extension?
Services using this will need three config variables:
- RELENG_NOTIFICATION_POLICY_ENDPOINT
- TASKCLUSTER_CLIENT_ID
- TASKCLUSTER_ACCESS_TOKEN
=> [releng_notification*] Notification create method 

src/releng_docs/develop/python-project.rst, src/releng_docs/index.rst, src/releng_docs/projects/releng-mapper.rst, src/releng_docs/projects/releng-notification-identity.rst, src/releng_docs/projects/releng-notification-policy.rst
Update the notification docs, migrate docs from relengapi for the mapper, and fix an incorrect command in documentation (should be ```./please tools update-dependencies <project>```).
=> releng_docs: Add mapper docs, update notification docs, fix incorrect command

lib/backend_common/backend_common/aws.py
Code is ported, exact same as [aws.py](https://github.com/mozilla/build-relengapi/blob/master/relengapi/lib/aws.py) except using cli_common for logging and removed wsme code.
Will need an AWS bucket to test.
=> backend_common: Migrate AWS.py plugin from relengapi

src/shipit_code_coverage/shipit_code_coverage/codecov.py
This way we can more easily identify builds on coveralls.io.
=> shipit_code_coverage: Use push ID as the Coveralls service number

src/releng_frontend/src/static/trychooser/index.html
Requires https://reviewboard.mozilla.org/r/166566/diff/ to land first, before being deployed.
=> Bug 1384482 - Trychooser: Drop Android API-15 in favor of API-16

src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py
If there are no changes in a directory, there's no mercurial changeset associated with it and thus no bugs. The Bugzilla query returns an emtpy result.
=> Don't fail if Bugzilla returns an empty result

src/releng_frontend/src/static/trychooser/index.html
The SDK and all of its accompanying tests are being removed from
mozilla-central in bug 1371065, after which this suite will no longer be
supported. In the mean time, it runs only one test, which no-one should have
any particular need to trigger.
=> Remove mochitest-jetpack suite from trychooser

src/shipit_static_analysis/shipit_static_analysis/clang.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py
This enables the previously ignored warnings (due to `-header-filter` misused) and creates some nicer issue comments in admin emails & MozReview.
=> shipit_static_analysis: Nicer MozReview comments.

src/shipit_uplift/shipit_uplift/coverage.py
The frontent will always request the latest changesets and the list of changesets doesn't change too much throughout the day, so this cache should be particularly effective.
=> shipit_uplift: Cache file coverage info

src/shipit_uplift/shipit_uplift/coverage.py, src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py, src/shipit_uplift/shipit_uplift/coverage_summary_by_changeset_impl.py
And add overall information to "/coverage/changeset" endpoint.
=> shipit_uplift: Remove coverage info for removed lines (as it was unused)

src/shipit_uplift/shipit_uplift/coverage.py
=> shipit_uplift: Don't fail requesting coverage info for a commit if we don't have info about the parent

src/shipit_uplift/shipit_uplift/coverage.py, src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
Fixes #609.
Unfortunately, there's an exception when I run this:
```
Traceback (most recent call last):
File "/nix/store/5y3riwfpxx4hx17b5ww6pw16rv68vri8-python3.5-Flask-Cache-0.13.1/lib/python3.5/site-packages/flask_cache/__init__.py", line 528, in decorated_function
cache_key = decorated_function.make_cache_key(f, *args, **kwargs)
File "/nix/store/5y3riwfpxx4hx17b5ww6pw16rv68vri8-python3.5-Flask-Cache-0.13.1/lib/python3.5/site-packages/flask_cache/__init__.py", line 381, in make_cache_key
timeout=_timeout)
File "/nix/store/5y3riwfpxx4hx17b5ww6pw16rv68vri8-python3.5-Flask-Cache-0.13.1/lib/python3.5/site-packages/flask_cache/__init__.py", line 350, in _memoize_version
version_data_list = list(self.cache.get_many(*fetch_keys))
File …
```
=> shipit_uplift: Retrieve coverage information in parallel with multiple threads

src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
Sometimes the same diff was parsed twice and a diff was not parsed at all, as the lambda was capturing `diff` at the wrong time.
=> shipit_uplift: Fix scope issue with threads

src/shipit_uplift/shipit_uplift/coverage.py
I've looked at a report and noticed there are files with these extensions that we were ignoring.
=> shipit_uplift: Add more extensions to the supported list

src/shipit_uplift/shipit_uplift/worker.py
The failing jobs were not actually being put in the `failed` queue. This means some jobs would be `pending` forever.
=> shipit_uplift: Fix worker's exception handling

src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
I'm seeing codecov.io often returning 500. It might be due to the fact that we are requesting too many files at the same time. Let's try setting a maximum number of threads (that is, basically, the maximum number of connections) to 4.
=> shipit_uplift: Set maximum number of workers loading from codecov.io to 4

src/releng_frontend/src/static/trychooser/index.html
Hi @garbas  
This pull request is in response to the Bug 940712 mentioned [here](https://bugzilla.mozilla.org/show_bug.cgi?id=940712)
I've fixed the favicon issue on the TryChooser page. Please merge this pull request
Thanks,
Aravind Kashyap
=> Fixed the Bug 940712. Basically added the favicon to the TryChooser page

nix/lib/default.nix
Fixes #643.
We are not setting this environment variable by default, which means we end up with a single gunicorn worker. Heroku suggests setting it to 2 or 3 for `free`, `hobby` and `standard-1x` dynos
=> Set WEB_CONCURRENCY env variable by default to 3

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_uplift/shipit_uplift/coverage.py, src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
=> shipit_code_coverage, shipit_uplift: Don't preload merge commits and directly return an error for them

src/shipit_code_coverage/shipit_code_coverage/codecov.py
When the task is triggered by pulse (that is, from a mozilla-central commit), we want to ignore talos and awsy (as they are not really test suites).
When we are generating the weekly per-test suite reports, we want to generate a report for talos too.
=> shipit_code_coverage: Add talos to weekly per-test suite reports

src/releng_frontend/src/static/trychooser/index.html, src/releng_frontend/src/static/trychooser/trychooser.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1411825
* Rename job
* Environment variable is now optional
* Test platform is required
=> Bug 1411825 - trychooser: Update browser-screenshots name and restrictions

lib/frontend_common/TaskclusterLogin.elm, lib/please_cli/please_cli/config.py, lib/please_cli/please_cli/run.py, lib/please_cli/please_cli/shell.py
- logout message never cleared the model
- taskcluster certificate comes in seconds not miliseconds
- tries to address problems in Bug 1407694[1]
- adds --taskcluster-client-id/--taskcluster-access-token options to
please run and shell subcommand. that would load configuration from
taskcluster secrets service.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1407694
=> frontend_common: taskcluster login was not reflacting its state

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/utils.py, src/shipit_code_coverage/tests/test_utils.py
=> shipit_code_coverage: Retry operations 5 times instead of 3, with a 120 second delay, and retry "mach build" too when it fails

src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Add support for JavaScript in the zero coverage reports

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/taskcluster.py, src/shipit_code_coverage/tests/test_taskcluster.py
`test-linux64-ccov` was hardcoded in `is_coverage_task`, so Windows coverage tasks were not being considered as coverage tasks.
=> shipit_code_coverage: Consider Windows coverage tasks as coverage tasks

src/shipit_uplift/shipit_uplift/api.py, src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py
By always using short revisions, we avoid duplicating cached results in case they are requested once in the long format and once in the short format.
=> shipit_uplift: Support using short revisions when retrieving coverage info for a changeset and always use short revisions

src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Check the future for mozilla-central cloning didn't fail before trying to build

src/shipit_code_coverage/tests/test_utils.py
This saves 10 minutes during tests 😄
=> shipit_code_coverage: Don't actually wait when testing the 'retry' function from utils

src/shipit_code_coverage/shipit_code_coverage/codecov.py
In the short time between bug 1431349 landing and updating the task to cope with its changes, we will need to copy the chrome-map.json in the src directory.
=> shipit_code_coverage: Temporarily copy chrome-map.json file from the obj directory to the src directory to avoid fallout when bug 1431349 lands

src/shipit_code_coverage/shipit_code_coverage/codecov.py
When the coverage build fails, `taskcluster.get_task` raises an exception and so we are not able to see the revision.
It would be useful to see the revision so that we can confirm the coverage build failed and we can check why it failed.
=> shipit_code_coverage: Log mercurial revision as soon as possible

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/taskcluster.py
This fixes #486 and fixes #781.
=> shipit_code_coverage: Stop building Firefox and use platform-specific chrome-map.json files to rewrite LCOV

src/shipit_code_coverage/shipit_code_coverage/utils.py
Fixes #771.
I will monitor failure rates to see if 30 seconds is too short.
=> shipit_code_coverage: Reduce waiting times to 30 seconds

src/shipit_uplift/settings.py, src/shipit_uplift/shipit_uplift/api.py
This PR also updates the name of the secret from CODECOV_TOKEN to CODECOV_ACCESS_TOKEN (it was already changed, but I forgot to update settings.py too).
=> shipit_uplift: Return 500 when coverage for a file couldn't be retrieved

src/releng_frontend/src/static/trychooser/index.html
Regarding the Mac OSX Static Analysis one: https://bugzilla.mozilla.org/show_bug.cgi?id=1411408
=> releng_frontend: Remove Mac OS X Static Analysis build and clarify win32 mingw32 description

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py
I've noticed sometimes the download is "successful", but we fail to use the downloaded ZIP files.
We should check if they are valid right away and retry the download when they aren't.
=> shipit_code_coverage: Retry download if the ZIP file is invalid

src/shipit_pulse_listener/shipit_pulse_listener/listener.py
`shipit_static_analysis` now needs a Phabricator DIFF id instead of a DREV.
Also the list of diffs on productions is already quite large, so we only analyse the new diffs (useful for a clean restart)
=> shipit-pulse-listener: Fixes to run Phabricator parsing on production

src/shipit_code_coverage/shipit_code_coverage/artifacts.py, src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/github.py, src/shipit_code_coverage/shipit_code_coverage/uploader.py
Fixes #813
This way, we don't have to worry about test tasks that haven't finished yet.
=> shipit_code_coverage: Make task triggered by the cron use the latest coverage build with finished tests

lib/cli_common/cli_common/utils.py, lib/cli_common/tests/test_utils.py, src/shipit_code_coverage/shipit_code_coverage/artifacts.py, src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/github.py, src/shipit_code_coverage/shipit_code_coverage/notifier.py, src/shipit_code_coverage/shipit_code_coverage/taskcluster.py, src/shipit_code_coverage/shipit_code_coverage/uploader.py, src/shipit_code_coverage/tests/test_artifacts.py, src/shipit_pulse_listener/shipit_pulse_listener/listener.py
=> shipit_pulse_listener: Retry retrieving coverage build multiple times before failing and fail without throwing exceptions

src/shipit_code_coverage/shipit_code_coverage/codecov.py
Fixes #821
Fixes #809
Couldn't find any other `tarfile` references in the repo.
This change is not covered in any of the `shipit_code_coverage` tests.
How does one test the `CodeCov` class?
=> shipit_code_coverage: Use tarfile.open as a context manager

src/shipit_uplift/shipit_uplift/coverage.py, src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py, src/shipit_uplift/shipit_uplift/coverage_by_dir_impl.py
My last PR https://github.com/mozilla-releng/services/pull/864 broke some of the `.format` calls. This made  `get /coverage/changeset/{changeset}` and other endpoints always return 500.
This will be in WIP until I test these changes properly.
Fixes #839
=> shipit_uplift: Use .format instead of %

src/shipit_code_coverage/shipit_code_coverage/artifacts.py, src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Use `args` and `kwargs` parameters of executor.submit

lib/backend_common/backend_common/auth0.py
If a user logs in for the first time in treeherder.mozilla.org, tools.taskcluster.net or https://mozilla-releng.net, they will get a prompt asking permission to access “full-user-credentials”. This is simply asking to access the user's taskcluster credentials but is a little bit scary and misleading. To that end, we are changing it to be `taskcluster-credentials`. Both taskcluster-tools[1] and treeherder[2] have been successfully switched to using `taskcluster-credentials`. Once we have this merged here, I will ask the IAM team to remove `full-user-credentials`.
[1] https://github.com/taskcluster/taskcluster-tools/pull/441
[2] https://github.com/mozilla/treeherder/pull/3227
=> Bug 1437116 - Change "full-user-credentials" scope to "taskcluster-credentials"

src/shipit_pulse_listener/shipit_pulse_listener/listener.py
This is breaking shipit-pulse-listener on staging when no new diff is loaded.
=> shipit-pulse-listener: Do not overwite latest_id to null

lib/cli_common/cli_common/command.py, lib/cli_common/tests/test_command.py, lib/cli_common/tests/test_utils.py
There's a `log.info` right before with more information, so we wouldn't lose anything here.
=> cli_common: Only log program name, to avoid Sentry ingoring too long messages

nix/tools/mercurial.nix
It is definitely unused in the code coverage project and as far as I can tell in the static analysis project too.
Sometimes it causes issues, such as:
```
hglib.error.CommandError: (1, b'ensuring https://hg.mozilla.org/mozilla-central@tip is available at /cache/mozilla-central
(existing repository shared store: /cache/mozilla-central-shared/8ba995b74e18334ab3707f27e9eb8f4e37ba3d29/.hg)
(pulling to obtain tip)
(purging working directory)', b'(using Mercurial 4.5)
(remote resolved tip to bccdc684210431c233622650a91454c09f6af9eb; result is not deterministic)
(revision already present locally; not pulling)
** Unknown exception encountered with possibly-broken third-party extension reviewboard
** which supports versions 4.2 of Mercurial.
** Please disable reviewboard and try your action again. …
```
=> nix: Don't use 'reviewboard' mercurial extension

src/shipit_code_coverage/default.nix
=> shipit_code_coverage: Remove gecko-env as it is no longer used

src/shipit_code_coverage/shipit_code_coverage/codecov.py, src/shipit_code_coverage/shipit_code_coverage/grcov.py, src/shipit_code_coverage/tests/test_grcov.py
I had removed the parameter from #909, but then realized we actually want it in some cases (that is, in the cases where we also pass the source directory).
This PR also disables the suite reporting for now, since it is unused.
=> shipit_code_coverage: Ignore not existing files in some cases

src/shipit_static_analysis/shipit_static_analysis/lint.py
Avoid crashing tasks like for bug https://reviewboard.mozilla.org/r/226050/
=> shipit-static-analysis: Support missing relative or absolute path in linter 

src/shipit_code_coverage/shipit_code_coverage/codecov.py
It was disabled a couple of days ago because I thought it wasn't being used, apparently it is for web-platform-tests.
=> Reenable suite generation

src/shipit_static_analysis/default.nix, src/shipit_static_analysis/shipit_static_analysis/cli.py, src/shipit_static_analysis/shipit_static_analysis/config.py, src/shipit_static_analysis/shipit_static_analysis/report/phabricator.py, src/shipit_static_analysis/shipit_static_analysis/revisions.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py, src/shipit_static_analysis/tests/conftest.py, src/shipit_static_analysis/tests/mocks/phabricator_diff_raw.json, src/shipit_static_analysis/tests/test_revisions.py
Needed to support Phabricator's multiple modes (hgcm, gtcm, gttr)
=> shipit-static-analysis: Use raw patch instead of mercurial revisions.

src/shipit_code_coverage/shipit_code_coverage/grcov.py, src/shipit_code_coverage/tests/test_grcov.py
It got lost in a refactoring, but codecov.py is using it for chunk_mapping generation (for which tests will be added soon).
=> shipit_code_coverage: Add source_dir parameter to files_list 

src/shipit_code_coverage/shipit_code_coverage/codecov.py
=> shipit_code_coverage: Log ActiveData errors and increase severity of codecov.io timeouts

src/shipit_static_analysis/shipit_static_analysis/lint.py, src/shipit_static_analysis/shipit_static_analysis/report/mozreview.py
Codespell comments are crashing the mozreview publication (`None` as a line number)
=> shipit-static-analysis: Fix mozlint line number format.

lib/please_cli/please_cli/config.py
I also submitted https://github.com/mozilla-releng/build-cloud-tools/pull/332 to add DNS for the staging app.
=> shipit-workflow: enable Heroku deployments

lib/backend_common/backend_common/auth0.py
It looks like Auth0 started setting proper response codes, at least I
hit 400 while hacking on something. This should handle the situation
when Auth0 API returns 400/500 errors
=> Use only OK Auth0 responses

nix/lib/default.nix, src/shipit_pulse_listener/shipit_pulse_listener/hook.py, src/shipit_pulse_listener/tests/test_hook.py
When a hook is triggered by cron, its payload is `{}`, so there's no `extra_env` property, so the trigger fails because the payload doesn't match the trigger schema.
The simplest fix is to make the extra_env the payload, this way tasks triggered by cron simply have no extra env, and tasks triggered by pulse listener have the extra env as the payload directly (and not as a property of the payload).
=> Fix payload for scheduled hooks

src/shipit_workflow/shipit_workflow/tasks.py
We probably need a firefox off-cycle partner workflow as well, but we haven't fully defined that yet. It'll probably look like ['promote_firefox_partners', 'push_firefox_partners'] or just ['promote_firefox_partners']. That flavor takes a promote action task ID so we don't redo the entire promote graph.
=> update the workflows

src/shipit_workflow/shipit_workflow/api.py
api.yml doesn't require it, let's do the same in the code!
=> shipit-workflow: release_eta is optional

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py, src/shipit_code_coverage/tests/test_taskcluster.py
Before this PR, we were downloading errored artifacts anyway and then failing with BadZipFile. With this PR, we are more precise with the error messages.
Here's an example invalid artifact: https://taskcluster-artifacts.net/FBdocjnAQOW_GJDOfmgjxw/0/public/test_info/code-coverage-grcov.zip.
=> shipit_code_coverage: Raise exception when the artifact status code is not 200

src/shipit_static_analysis/shipit_static_analysis/__init__.py, src/shipit_static_analysis/shipit_static_analysis/clang/format.py, src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py, src/shipit_static_analysis/shipit_static_analysis/lint.py, src/shipit_static_analysis/shipit_static_analysis/report/mail.py, src/shipit_static_analysis/shipit_static_analysis/report/mozreview.py, src/shipit_static_analysis/shipit_static_analysis/report/phabricator.py, src/shipit_static_analysis/shipit_static_analysis/revisions.py, src/shipit_static_analysis/shipit_static_analysis/utils.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py, src/shipit_static_analysis/tests/conftest.py, src/shipit_static_analysis/tests/mocks/config.yaml, src/shipit_static_analysis/tests/test_clang.py, src/shipit_static_analysis/tests/test_reporter_mail.py, src/shipit_static_analysis/tests/test_reporter_mozreview.py
The decision tree to use **clang-*** analyzers became a bit more complex (available from config + C/C++ files detection + `mach ` setup), so it makes sense to have a more generic setup.
This PR is basically a backport from the first part of #861 (to be reworked & merged this week). Merging first the generic analyzer + generic patch building would simplify a lot the rework of #861.
=> shipit-static-analysis: Support generic analyzers

src/shipit_static_analysis/default.nix, src/shipit_static_analysis/shipit_static_analysis/clang/__init__.py, src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py, src/shipit_static_analysis/shipit_static_analysis/lint.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py
Mach does not allow to use `./mach artifact toolchain --from-build` in a Taskcluster environment.
=> shipit-static-analysis: Download clang build directly from Taskcluster index

.taskcluster.yml, lib/please_cli/please_cli/base_image.py, lib/please_cli/please_cli/config.py, lib/please_cli/please_cli/decision_task.py, lib/please_cli/please_cli/utils.py, nix/docker/Dockerfile, please, src/releng_docs/deploy/weekly-releases.rst
* make it possible to build docker image again. this was broken since we switched development environment to docker. now it is possible to build docker image from docker container. this will also allow us in the near future to build base docker images on each commit.
* With move to nix sandbox and docker base-image command was broken.
this commit included a fix for this since it installs docker inside
base image and forwards docker socket. fixes #1003
* Stores credentials and other secrets in taskcluster secrets service.
That makes the command easier to use.
* weekly release documentation has been updated how to use new command
* docker container will now has a hash at the end of the name calculated
from current directory and branch. That means we can use multiple
containers across …
=> please_cli: multiple base docker image changes

lib/backend_common/requirements-dev.txt, lib/backend_common/requirements-extra.json, lib/cli_common/requirements-dev.txt, lib/cli_common/requirements-extra.json, lib/please_cli/requirements.txt, src/shipit_uplift/requirements-dev.txt, src/shipit_uplift/requirements.nix, src/shipit_uplift/requirements.txt, src/shipit_uplift/requirements_frozen.txt, src/shipit_uplift/shipit_uplift/api.py, src/shipit_uplift/shipit_uplift/coverage.py, src/shipit_uplift/shipit_uplift/coverage_by_changeset_impl.py, src/shipit_uplift/shipit_uplift/coverage_for_file_impl.py, src/shipit_uplift/tests/conftest.py, src/shipit_uplift/tests/test_coverage.py
Fixes #856 and fixes #862.
We are blocked on updating to aiohttp 3 because of the Taskcluster library (https://github.com/taskcluster/taskcluster-client.py/issues/96). aiohttp 3 would be needed in order to do `async with aiohttp.request` without leaks.
If we can't upgrade to aiohttp 3 soon enough, we should switch to using a aiohttp session directly (#863).
=> shipit_uplift: Switch to using async IO for coverage endpoints

src/shipit_code_coverage/shipit_code_coverage/codecov.py
`grcov` is already using all CPU cores, so using multiple threads here is a very limited improvement (especially at the moment, since we're generating just one report :P). I'd like to just remove it and simplify the code.
=> shipit_code_coverage: Stop using multiple threads to generate suite reports

lib/please_cli/please_cli/config.py, src/shipit_code_coverage/shipit_code_coverage/secrets.py, src/shipit_code_coverage/shipit_code_coverage/uploader.py, src/shipit_uplift/shipit_uplift/coverage.py, src/shipit_uplift/shipit_uplift/secrets.py
With this, we'll be able to enable shipit_code_coverage on production.
=> shipit_code_coverage, shipit_uplift: Make the GitHub repository a configurable secret

src/shipit_static_analysis/shipit_static_analysis/lint.py
From [Sentry Error](https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/3848806/)
=> shipit-static-analysis: Fix lint issue building with double path variable

src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py, src/shipit_static_analysis/tests/mocks/config.yaml
[Sentry Error](https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/3608196/)
Fixes #1060.
=> shipit-static-analysis: Do not check clang-tidy -* is present.

src/releng_frontend/src/static/trychooser/index.html
- These task names were not working anymore, probably due to recent changes; it is now necessary to explicitly set the architecture's name.
- Also added the ARM64 simulator task, which is now interesting to us.
=> Update Spidermonkey task names in trychooser

src/shipit_pulse_listener/requirements.txt, src/shipit_pulse_listener/shipit_pulse_listener/listener.py, src/shipit_pulse_listener/tests/test_code_coverage_listener.py
Depends on #1122.
Fixes #1115.
=> shipit_pulse_listener: Remove old task check, as it's no longer required with idempotent coverage task

src/shipit_workflow/shipit_workflow/api.py, src/shipit_workflow/shipit_workflow/api.yml
This will be used by the UI to find shipped releases in order to
generate a list of suggested partials.
=> shipit-workflow: filter releases API

src/shipit_code_coverage/default.nix
The production hook doesn't work as it requires scopes that should be defined only for staging.
=> shipit_code_coverage: Make hook scopes depend on the branch (staging or production)

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py, src/shipit_code_coverage/tests/test_taskcluster.py
Fixes #1134
Removes 
- `get_last_task` function from `taskcluster.py`  file
- its associated tests from `test_taskcluster.py` file
=> shipit_code_coverage: Remove get_last_task function from taskcluster.py

src/shipit_code_coverage/shipit_code_coverage/taskcluster.py, src/shipit_code_coverage/tests/test_taskcluster.py
The code coverage build is a debug build, but named as an opt build.
In https://bugzilla.mozilla.org/show_bug.cgi?id=1457393, we are renaming it to identify it as a debug build. For a while, the code coverage task will have to support both names.
=> shipit_code_coverage: Look for debug build first and fallback on opt build if the debug build doesn't exist

src/shipit_code_coverage/shipit_code_coverage/report_generators.py, src/shipit_code_coverage/tests/test_report_generators.py
Bad variable rename in https://github.com/mozilla-releng/services/commit/432ca36d23aa0016151e5d55085a763956c64b84
=> shipit_code_coverage: Fix variable name in report_generators

src/shipit_code_coverage/shipit_code_coverage/artifacts.py, src/shipit_code_coverage/tests/test_artifacts.py
We are filtering the tasks to download in download_all, but then using the original list when actually downloading the artifacts.
=> shipit_code_coverage: Actually use the filtered task list when downloading artifacts

lib/please_cli/please_cli/run.py, please
This method has several advantages:
1. Does not bind unecessary ports
2. Previously binded port are automatically binded on `localhost`, so the urls continue working as is
3. The docker container also have access to the host computer network as `localhost`, so we can use SSH tunneling (needed for `shipit-code-coverage-backend` development)
4. Seems to avoid the port binding error sometimes encountered
Tested on releng_docs, shipit-uplift, postgresql, shipit-frontend, shipit-static-analysis, shipit-code-coverage-backend.
We should probably push this to staging before merging, in order to test the Taskcluster compatibility
Additional official dock on [--network=host](https://docs.docker.com/network/host/)
=> please: Use host networking instead of binding ports

src/shipit_workflow/shipit_workflow/api.py, src/shipit_workflow/shipit_workflow/api.yml
In order to fetch l10n info for partials, we need to know the revision of a particular build. This way we can stop using *_RELEASE tags in the UI.
=> shipit-workflow: filter by build_number

src/shipit_workflow/shipit_workflow/tasks.py
We renamed `ownTaskId` to `taskGroupId` recently.
=> shipit-workflow: fix taskGroupId input

src/shipit_workflow/shipit_workflow/tasks.py
CoT fails to validate action tasks with ACTION_TASK_GROUP_ID set. We can
drop this in favor of the fact that ACTION_TASK_GROUP_ID is set to
taskGroupId by
https://hg.mozilla.org/mozilla-central/rev/d4643b526038#l1.14
=> shipit-workflow: do not set ACTION_TASK_GROUP_ID

src/shipit_workflow/shipit_workflow/release.py
We shouldn't ever hit this in production, but I've been pushing to try with the default version from nightly, and it was producing versions like `62.0a4.1`.
=> Correctly bump the version used on nightly.

src/releng_docs/projects/shipit-static-analysis.rst, src/shipit_pulse_listener/shipit_pulse_listener/listener.py, src/shipit_static_analysis/shipit_static_analysis/report/phabricator.py, src/shipit_static_analysis/shipit_static_analysis/revisions.py, src/shipit_static_analysis/tests/test_reporter_mail.py, src/shipit_static_analysis/tests/test_revisions.py
`shipit_static_analysis` is expecting `<REVISION_ID>:<DIFF_PHID>`, while `shipit_pulse_listener` was sending `<DIFF_ID>:<DIFF_PHID>`, which was causing problems (see #1166).
And actually, you can get `<REVISION_ID>` from `<DIFF_PHID>`, so you can just pass `<DIFF_PHID>` to `shipit_static_analysis` and have it get `<REVISION_ID>` by itself with an API call.
=> shipit_static_analysis: Replace bugged revision ID parameter with an internal API call.

src/releng_docs/projects/shipit-static-analysis.rst
Fixes:
```
[nix-shell:/app/src/shipit_static_analysis]$ shipit-static-analysis \
>   --taskcluster-secret=repo:github.com/mozilla-releng/services:branch:staging \
>   --cache-root=/app/tmp
shipit_static_analysis.config: Loaded configuration from mozilla-central
Traceback (most recent call last):
File "/tmp/tmp.v87BoCgR0a/bin/shipit-static-analysis", line 11, in <module>
load_entry_point('shipit-static-analysis', 'console_scripts', 'shipit-static-analysis')()
File "/nix/store/wy78qnkvl1lw7p8vw4zpgqhp642w38vj-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/nix/store/wy78qnkvl1lw7p8vw4zpgqhp642w38vj-python3.5-click-6.7/lib/python3.5/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File …
```
=> releng-docs: Fix shipit-static-analysis docs

src/shipit_static_analysis/shipit_static_analysis/revisions.py, src/shipit_static_analysis/tests/conftest.py, src/shipit_static_analysis/tests/test_revisions.py
I also added a unit test that reproduce a common situation in static analysis: when a patch across multiple revisions is analyzed (through mercurial), the bot should list modified files across the full diff, and not the last revision only.
So i created a branch in a dummy repo with some commits to reproduce this. Only the commits from the branch are detected
=> shipit-static-analysis: Load full mercurial patch to detect files changes, fixes #1192

lib/cli_common/cli_common/log.py, lib/please_cli/please_cli/build.py, lib/please_cli/please_cli/check_cache.py, lib/please_cli/please_cli/config.py, lib/please_cli/please_cli/decision_task.py, lib/please_cli/please_cli/deploy.py, lib/please_cli/please_cli/nagios_config.py, lib/please_cli/please_cli/terraform_route53_config.py, nix/lib/default.nix
This commit does NOT implement sub-projects.
What it brings is a possibility to deploy similar nix derivations (variations) to multiple different locations.
As an example it could be that project needs to deploy to HEROKU web dyno and also to HEROKU worker dyno. It would deploy very similar docker image where majority of the code can be cached.
This feature should not increase build times.
=> please_cli: multiple deployments per project

src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py, src/shipit_static_analysis/tests/conftest.py, src/shipit_static_analysis/tests/test_clang.py
The string "Enabled checks:" can move in the mach static-analysis command output, so we cannot rely anymore on it, otherwise we miss some issues.
=> shipit-static-analysis: Remove "enabled checks" string detection in clang tidy, refs #1166

src/shipit_static_analysis/shipit_static_analysis/__init__.py, src/shipit_static_analysis/shipit_static_analysis/clang/format.py, src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py, src/shipit_static_analysis/shipit_static_analysis/lint.py, src/shipit_static_analysis/shipit_static_analysis/report/base.py, src/shipit_static_analysis/shipit_static_analysis/report/debug.py, src/shipit_static_analysis/shipit_static_analysis/report/mozreview.py, src/shipit_static_analysis/shipit_static_analysis/report/phabricator.py, src/shipit_static_analysis/shipit_static_analysis/revisions.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py, src/shipit_static_analysis/tests/conftest.py, src/shipit_static_analysis/tests/test_issues.py, src/shipit_static_analysis/tests/test_reporter_debug.py, src/shipit_static_analysis/tests/test_reporter_mozreview.py
Fixes #1166.
* Decrement `nb_lines` by 1 for Phabricator to remove the offset on display
* Use a different bug report url for Phabricator (still pointing at our Github Issues, only the comment changes)
* Introduces a new **debug reporter**, always activated, that:
* logs all the issues (publishable & silent)
* build a full json report, stored in the Taskcluster public artifacts dir (already used for diffs)
The debug reports would be used through the taskcluster index API + a small frontend to be built
=> shipit-static-analysis: Phabricator Fixes, refs #1166

nix/gecko_env.nix
As static.rust-lang.org is date based, we cannot provide a specific version.
=> nix: Pin rust to 1.26.2 in gecko-env

src/shipit_static_analysis/shipit_static_analysis/clang/tidy.py, src/shipit_static_analysis/shipit_static_analysis/lint.py, src/shipit_static_analysis/tests/test_clang.py, src/shipit_static_analysis/tests/test_lint.py
Currently, we export review messages with `.capitalize()`. This causes them to be transformed from:
> Please use ChromeUtils.defineModuleGetter instead of XPCOMUtils.defineLazyModuleGetter
into:
> Please use chromeutils.definemodulegetter instead of xpcomutils.definelazymodulegetter
which is obviously not ideal.
This change should fix #997 on MozReview and Phabricator, for both `clang-tidy` and `mozlint` issues.
@La0 please take a look.
=> shipit_static_analysis: Only .capitalize() the first letter of a defect message, not the full message.

nix/lib/default.nix, src/shipit_pulse_listener/shipit_pulse_listener/hook.py, src/shipit_pulse_listener/shipit_pulse_listener/listener.py, src/shipit_pulse_listener/tests/test_code_coverage_listener.py, src/shipit_static_analysis/default.nix, src/shipit_static_analysis/shipit_static_analysis/cli.py, src/shipit_static_analysis/shipit_static_analysis/revisions.py, src/shipit_static_analysis/shipit_static_analysis/workflow.py, src/shipit_static_analysis/tests/conftest.py, src/shipit_static_analysis/tests/test_reporter_debug.py, src/shipit_static_analysis/tests/test_reporter_mail.py, src/shipit_static_analysis/tests/test_reporter_mozreview.py, src/shipit_static_analysis/tests/test_revisions.py, src/shipit_static_analysis/tests/test_workflow.py
The idea here is to index Taskcluster tasks triggered by pulse listener, as soon as they are created, and using extra data from `triggerHook` payload.
Static analysis would use this feature to index tasks with their analysis ID (mozreview ID or phabricator DIFF ID)
=> Support custom Taskcluster routes

nix/gecko_env.nix
=> nix: Update rust to 1.28.0-beta6 for gecko-env

src/shipit_static_analysis/shipit_static_analysis/report/base.py, src/shipit_static_analysis/tests/test_reporter_mozreview.py
=> mach lint is doing more than only js/python (yaml, spell, etc)

src/shipit_code_coverage_crawler/setup.py, src/shipit_code_coverage_crawler/shipit_code_coverage_crawler/cli.py, src/shipit_code_coverage_crawler/shipit_code_coverage_crawler/secrets.py
This is adding an entry point for the shipit-code-coverage-crawler project.
After this PR is merged, you should be able to run the project like this:
`./please shell shipit-code-coverage-crawler`
In the shell created:
`shipit-code-coverage-crawler --cache-root tmp`
=> shipit_code_coverage_crawler: Add an entry point script for shipit-code-coverage-crawler

lib/please_cli/please_cli/run.py
=> please_cli: Add name of the project to the exception thrown when running a not-runnable application

lib/cli_common/cli_common/taskcluster.py, lib/please_cli/please_cli/config.py, src/shipit_workflow/settings.py
cli_common.taskcluster.get_secrets() when called wit `existing` prefers
the Taskcluster secrets over `existing`. This patch should change the
behaviour, so we can override the shared TC secrets with environment
variables per project, that will be set by Dockerflow.
=> shipit-workflow: prefer env variables

src/shipit_workflow/shipit_workflow/api.py, src/shipit_workflow/shipit_workflow/models.py, src/shipit_workflow/shipit_workflow/tasks.py
The action specification[1] documents this as being set to the decision                                                                                                                                            
task id of the task that defined the actions.                                                                                                                                                                      
There is also discussion in scriptworker docs[2] suggesting that it is set                                                                                                                                         
differently for release promotion tasks, so that the created tasks get …
=> shipit-workflow: Use decision task for in action context's `taskGroupId`.

src/shipit_workflow/shipit_workflow/api.py
This prevents the decorator from swallowing the decorated function's exceptions.
=> shipit-workflow: don't hide decorated exceptions

lib/please_cli/please_cli/base_image.py, lib/please_cli/please_cli/config.py, lib/please_cli/please_cli/decision_task.py, lib/please_cli/please_cli/deploy.py
This allows us to override docker repos we use to push images. This is
required by dockerflow, which expects images under mozilla/.
=> please_cli: use docker repos per project/channel

lib/please_cli/please_cli/config.py, lib/please_cli/please_cli/run.py, nix/default.nix
While working on #1393 i noticed that projects requiring redis stopped working since 8b6cef69a.
So i added redis in `PROJECTS_CONFIG` and into the `please_cli` build exactly like postgresql.
I also added a check for projects depending on redis.
This PR is needed for next release.
=> please_cli: Support redis.

lib/please_cli/please_cli/config.py
This update the URL we actually use for dockerflow
=> shipit/api: set staging URL

src/uplift/bot/default.nix
We have the `*` email scope now, so we should not request anymore specific addresses.
Triggered because @jankeromnes was added to the recipient list
=> uplift/bot: Enable mail notifications for everyone.

src/shipit_code_coverage/shipit_code_coverage/chunk_mapping.py, src/shipit_code_coverage/shipit_code_coverage/codecov.py
This breaks the log waiting times after the artifact downloading is done.
=> shipit_code_coverage: Add more logging

nix/gecko_env.nix
debug flag must be enabled by default for our static-analysis
environment.
Fixes #836.
=> shipit_static_analysis: Enable the debug option build by default

nix/gecko_env.nix
In order to keep the build environment clean we should remove the
unnecessary clang references.
=> shipit_static_analysis: Remove unnecessary clang references

lib/cli_common/cli_common/phabricator.py, src/shipit_code_coverage_backend/shipit_code_coverage_backend/api.py, src/shipit_code_coverage_backend/tests/conftest.py, src/shipit_code_coverage_backend/tests/test_phabricator.py, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/static_analysis_bot/workflow.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/test_reporter_mail.py, src/staticanalysis/bot/tests/test_revisions.py
* Move Phabricator api class from static analysis to common
* Use that class in code coverage backend & sa bot
* Fixes #1214 by switching to base revision when available
* PhabricatorRevision no longer relies on PhabricatorReporter : we can run the bot with phabricator credentials, but without posting reviews (staging can now use production phabricator data and stay silent)
=> Common Phabricator API client

nix/gecko_env.nix
Reverts mozilla/release-services#1437
Unfortunately it looks like they were required: [log.txt](https://github.com/mozilla/release-services/files/2329117/log.txt)
=> Revert "shipit_static_analysis: Remove unnecessary clang references"

nix/nixpkgs-mozilla.json
This updates `nixpkgs-mozilla.json` in order to allow a new target to be specified to `rust`.
=> Update nixpkgs-mozilla.json to revision 65ef92a7f9f1d5.

src/shipit_code_coverage/default.nix
This changes the schedule for running `shipit-code-coverage` to be daily instead of weekly.
=> shipit_code_coverage: Schedule chunk mapping generation to run daily

.gitignore, nix/gecko_env.nix, src/staticanalysis/bot/static_analysis_bot/__init__.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/infer/__init__.py, src/staticanalysis/bot/static_analysis_bot/infer/infer.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/static_analysis_bot/workflow.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/mocks/infer-issues.txt, src/staticanalysis/bot/tests/mocks/infer-output.txt, src/staticanalysis/bot/tests/mocks/infer-repeats.txt, src/staticanalysis/bot/tests/test_infer.py
This introduces `infer` into the static-analysis bot. When a `.java` file is part of a revision, it is passed to the `./mach static-analysis check-java` command.
=> Enabled the static analysis of java files.

src/shipit/frontend/src/views/NewRelease/index.js
I broke this when adding support for Thunderbird, as I only tested it with suggested revision.
=> [shipit] Fix setting a revision manually.

src/releng_mapper/default.nix, src/releng_mapper/requirements.nix, src/releng_mapper/requirements.txt, src/releng_mapper/requirements_frozen.txt
On heroku there is a limit of 30 seconds timeout for a request to finish. That timeout can be extended if you stream the response. Streaming with gunicorn can only work if you use an async worker class (eg. like gevent).
With streaming a timeout gets renewed to 50 seconds each time something is streamed. That way we can avoid default 30 second timeout.
=> releng-mapper: using gevent as worker class for gunicorn

src/staticanalysis/bot/static_analysis_bot/infer/__init__.py, src/staticanalysis/bot/static_analysis_bot/report/base.py
This fixes the following errors:
* `./mach configure` failing when configuring the android build
* error regarding `InferIssues` not being supported
=> staticanalysis/bot: Fix infer errors.

src/uplift/backend/uplift_backend/api.yml, src/uplift/bot/requirements.nix, src/uplift/bot/requirements_frozen.txt, src/uplift/bot/uplift_bot/bugzilla.py, src/uplift/bot/uplift_bot/cli.py, src/uplift/bot/uplift_bot/merge.py, src/uplift/bot/uplift_bot/sync.py
When a Firefox patch is requested be uplifted, but it doesn't apply cleanly, we:
1. Remove the "approval-mozilla-{beta,release,esr*}" flag from attachments
2. Post a comment explaining that the merge failed, with details
3. Needinfo the person who requested the uplift
TODO:
=> uplift/bot: Cancel uplift requests when merging fails.

lib/please_cli/please_cli/config.py, src/shipit/frontend/default.nix
add auth0 domains to allow script-src and background re-auth
=> shipit/frontend: fix CSPs

src/staticanalysis/bot/static_analysis_bot/clang/__init__.py
clang-tidy is no longer build in mozilla-central repo in 5 moths, but
in autoland is build on a periodic basis.
=> staticanalysis/bot: Download the artifact from the autoland repo.

src/staticanalysis/bot/static_analysis_bot/infer/__init__.py
linux64-infer is not in the same namespace with the android-*
artefacts, so we need to use distinct namespaces when dealing with the
link request.
=> Infer - Download the artefacts from their appropriate places.

src/staticanalysis/bot/static_analysis_bot/report/phabricator.py
Stop mentioning 'shipit_static_analysis', add a 'app:staticanalysis/bot' label and add a 'SUMMARY' placeholder in the title so that developers give a meaningful title.
=> staticanalysis/bot: Update prefilled issue format

src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/static_analysis_bot/clang/tidy.py, src/staticanalysis/bot/tests/mocks/clang-issues.txt, src/staticanalysis/bot/tests/test_clang.py
Now that MozReview is gone, and that comments are no longer synced to Bugzilla, we can leverage markdown.
In fact, our comments are already treated as markdown by Phabricator, causing our snippets to occasionally look a bit strange, because part of the snippet is outside the code block:
https://phabricator-dev.allizom.org/D697#inline-17044
=> staticanalysis/bot: Properly format markdown snippets in clang-tidy and clang-format comments.

src/staticanalysis/bot/static_analysis_bot/infer/__init__.py
The current expiration for a signedURL is 15 minutes. Since we are downloading two large artifacts this might take longer, this leads to authentication failures.
=> Change the expiration for signedURL

src/staticanalysis/bot/static_analysis_bot/clang/__init__.py, src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/static_analysis_bot/clang/tidy.py, src/staticanalysis/bot/static_analysis_bot/workflow.py, src/staticanalysis/bot/tests/conftest.py
From https://bugzilla.mozilla.org/show_bug.cgi?id=1495641
=> staticanalysis/bot: Fix clang-tidy & clang-format paths

src/releng_frontend/src/static/trychooser/index.html
=> releng_frontend: Add a note that win64 mingw clang doesn't run tests

lib/cli_common/requirements-dev.txt
=> cli_common: Lock taskcluster to 4.0.1

lib/please_cli/please_cli/__init__.py, lib/please_cli/please_cli/utils.py
Changed name param of 'click.group' so that `./please --help` does not show `.please-wrapper`.
=> please_cli: Changed name parameter of 'click.group' to show correct output (#1071)

src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/mocks/phabricator_createinline.json, src/staticanalysis/bot/tests/mocks/phabricator_transaction_search.json, src/staticanalysis/bot/tests/test_reporter_phabricator.py
Using the suggestion from #1271 (and also swapping the diff URL and the bug report URL).
=> staticanalysis/bot: Slightly improve the clang-format patch URL message.

src/codecoverage/bot/code_coverage_bot/codecov.py, src/codecoverage/bot/code_coverage_bot/taskcluster.py
Fixes #1442.
Depends on #1607.
=> codecoverage/bot: Ingest coverage artifacts from Android

src/codecoverage/backend/codecoverage_backend/__init__.py, src/codecoverage/backend/codecoverage_backend/datadog.py, src/codecoverage/backend/codecoverage_backend/secrets.py, src/codecoverage/backend/codecoverage_backend/services/active_data.py, src/codecoverage/backend/codecoverage_backend/v2/base.py, src/codecoverage/backend/codecoverage_backend/v2/path.py, src/codecoverage/backend/requirements.nix, src/codecoverage/backend/requirements.txt, src/codecoverage/backend/requirements_frozen.txt, src/codecoverage/backend/tests/conftest.py, src/codecoverage/backend/tests/test_coverage.py
=> Add Datadog timers for Active Data requests

src/staticanalysis/bot/static_analysis_bot/infer/__init__.py
As it can be seen in automation, https://searchfox.org/mozilla-central/source/taskcluster/ci/build/android.yml#16, we need to set 'GRADLE_USER_HOME’, otherwise it may be possible that gradle would fail generating some targets.
=> Add 'GRADLE_USER_HOME' environment variable since it's needed in automation.

src/staticanalysis/bot/static_analysis_bot/__init__.py, src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/static_analysis_bot/clang/tidy.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/infer/infer.py, src/staticanalysis/bot/static_analysis_bot/lint.py, src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/static_analysis_bot/report/debug.py, src/staticanalysis/bot/static_analysis_bot/report/mail.py, src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/static_analysis_bot/workflow.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/test_clang.py, src/staticanalysis/bot/tests/test_issues.py, src/staticanalysis/bot/tests/test_reporter_mail.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py, src/staticanalysis/bot/tests/test_workflow.py
=> Use improvement patches built by analyzers

src/codecoverage/bot/code_coverage_bot/taskcluster.py, src/codecoverage/bot/tests/test_taskcluster.py
`build-win64-ccov/debug` doesn't contain `windows`, so we have to adjust `get_platform`.
=> codecoverage/bot: Fix detection of Windows platforms

src/staticanalysis/bot/static_analysis_bot/infer/__init__.py
Do not start 'gradle' in daemon-mode since on some configurations, like 'nix' on top of a debian docker image this fails.
=> Do not start gradle in 'daemon mode'

src/codecoverage/bot/code_coverage_bot/chunk_mapping.py
The best solution would be to use a secret here so it's configurable easily, but this is the smallest possible fix for the next release.
=> codecoverage/bot: Update ActiveData query URL

nix/gecko_env.nix
Example of a [failing task](https://tools.taskcluster.net/groups/ViB07SzrTQ-XeHf8yv2Bxg/tasks/ViB07SzrTQ-XeHf8yv2Bxg/runs/0/logs/public%2Flogs%2Flive.log)
=> staticanalysis/bot: Update rust-cbindgen to 0.6.6

src/shipit/api/shipit_api/__init__.py
This should stop using the TC credentials from the secrets and fix the "Auth failures".
=> shipit/api: Use env vars for TC IRC notifications

src/codecoverage/bot/code_coverage_bot/chunk_mapping.py, src/codecoverage/bot/code_coverage_bot/taskcluster.py, src/codecoverage/bot/tests/test_taskcluster.py
=> codecoverage/bot: Use a placeholder chunk for build tasks to avoid having empty chunks

src/shipit/api/shipit_api/api.py, src/shipit/api/shipit_api/api.yml
In the future we will need to update the release status explicitly from
a in-tree scheduled task, so we mark a release as completed only after
all required tasks are done (bouncer, tests, etc).
=> shipit/api: update release status

src/uplift/bot/uplift_bot/bugzilla.py, src/uplift/bot/uplift_bot/cli.py, src/uplift/bot/uplift_bot/sync.py
Eventually, Uplift Bot should be able to cancel uplift requests that aren't valid.
However, until we're sufficiently confident that Uplift Bot can correctly identify invalid uplifts (without false positives), we should let it post a comment on Bugzilla, but without cancelling the `approval-mozilla-{beta,release,esr*}` flag, nor setting needinfos.
This will allow us to soft-launch Uplift Bot, and go through a trial phase where we evaluate / iterate on its results, before giving it full cancellation power.
=> uplift/bot: Add a BUGZILLA_COMMENT_ONLY setting in order to report failed uplifts without cancelling requests.

src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/test_clang.py, src/staticanalysis/bot/tests/test_issues.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
Needed to activate clang-format code review on `dom/media/*`
=> staticanalysis/bot: Filter clang-format publishable issues by their path 

lib/please_cli/please_cli/run.py
#914 
this PR show all of the error output, instead of giving suggestion
```
'Please run:\n\n'	
'    ./please run postgresql\n\n'	
'in a separate terminal.
```
the error is because to run postgres, it run `psql` command using nix-shell, and nix-shell have checkPhase which includes pylint and flake8 before running the actual command. These checkPhase are able to throw error, however in the code, whatever error thrown, it will only show one suggestion. I changed it to show the output instead, so we can deduce what error is causing it to fail from the output
=> please-cli: fix misleading error output

src/staticanalysis/bot/static_analysis_bot/report/phabricator.py
To avoid [this edge case](https://phabricator.services.mozilla.com/D12784#313910) where a patch with clang-format issues not publishable (due to paths not covered) is published even though the linked issues are silent
Fixes #1704
=> staticanalysis/bot: Do not publish patches without matching issues.

src/shipit/api/shipit_api/api.py
This sorts releases by their version, so we don't rely on the DB ordering.
=> shipit/api: sort releases by version

src/shipit/frontend/src/configs/production.js, src/shipit/frontend/src/views/NewRelease/index.js
In case of RC releases we may have versions from different branches. In order to
fetch the l10n changesets, we need to detect the branch by matching the version
to a particular pattern and use a different repo in that case.
=> shipit/frontend: handle RC properly

src/shipit/api/shipit_api/config.py
Making this commit as instructed in https://github.com/mozilla-releng/ship-it/blob/47b9c089a117b0066b50c4624af57f6e4970c564/kickoff/config.py#L1 for our upcoming release
=> Nightly 66: Merge and deply when 66 builds are available for all locales

lib/cli_common/cli_common/phabricator.py, src/codecoverage/bot/code_coverage_bot/codecov.py, src/codecoverage/bot/code_coverage_bot/phabricator.py, src/codecoverage/bot/code_coverage_bot/secrets.py, src/codecoverage/bot/tests/conftest.py, src/codecoverage/bot/tests/fixtures/phabricator_harbormaster_queryautotargets.json, src/codecoverage/bot/tests/fixtures/phabricator_harbormaster_queryautotargets_lint.json, src/codecoverage/bot/tests/fixtures/phabricator_harbormaster_sendmessage.json, src/codecoverage/bot/tests/fixtures/phabricator_harbormaster_sendmessage_lint.json, src/codecoverage/bot/tests/fixtures/phabricator_revision_search.json, src/codecoverage/bot/tests/test_phabricator.py
This is a temporary implementation until https://bugzilla.mozilla.org/show_bug.cgi?id=1487843 is resolved. The implementation won't change much after that, so most of the code will still be useful.
=> codecoverage/bot: Upload coverage data to Phabricator using arcanist autotarget

nix/docker/profile.sh, nix/setup.sh, nix/templates/backend-json-api/hooks/post_gen_project.sh, please
Prevent masking of exit code:
```
-export USER=`whoami`
+USER=$(whoami)
+export USER
```
`-o` -> `||` as `-o` can have undefined behaviour
`which` -> `command -v` as which is not guaranteed to be present.
`echo -n` -> `printf` because echo in `sh` doesn't have flags.
Some quoting and redirection fixes.
=> Shellcheck safety checks

lib/cli_common/cli_common/taskcluster.py, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/static_analysis_bot/report/debug.py, src/staticanalysis/bot/static_analysis_bot/report/mail.py, src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/static_analysis_bot/workflow.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/test_reporter_mail.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py, src/staticanalysis/bot/tests/test_workflow.py
The goal is to display nicely the patch in browser (see #1696 ) :
- use `text/plain` content type through manual TC publication
- display link with Markdown formatting on phabricator
- remove clang-format inline comments
=> staticanalysis/bot: Better clang-format patch publication

src/shipit/api/shipit_api/release.py
This fixes the case when we have no partials (Fennec) but stil want to
use the `is_rc()` function
=> shipit/api: do not iterate over None

lib/cli_common/cli_common/taskcluster.py, src/staticanalysis/bot/static_analysis_bot/cli.py
This is needed by Taskcluster so that docker-worker gets the "done" status.
Fixes #1755
=> cli_common: mark artifact as completed when uploaded manually

src/staticanalysis/bot/static_analysis_bot/workflow.py
Fixes #1722.
Explanation from IRC:
> 14:33:29 janx> marco, bastien: wow, I think I finally understood the "race condition" with before/after and debug logs
> 14:34:15 janx> `issue.lines_hash` is memoized, and only computed when you call `issue.__hash__()`. To compute it, it opens the file, and hashes the content of the line
> 14:35:06 janx> in before/after, we first create a collection of issues, then *apply the patch*, and create another collection of issues, and then we compare the two collections by computing the hashes
> 14:35:43 janx> but it's too late to compute the correct hashes for the first collection of issues (the "before_issues"), because we've already applied a patch and potentially changed the content of the lines it will try to hash
> 14:36:42 janx> that was a big "aha!" …
=> staticanalysis/bot: Fix many strange false positives in BEFORE_AFTER heuristic.

src/shipit/api/shipit_api/models.py, src/shipit/api/shipit_api/release.py, src/shipit/api/tests/test_release.py
I'm still working on other parts of bug 1492033 but wanted to get this up for comment. We'll need partner repacks on for b8 and higher, release, and esr, which I've expressed as not b1-b7.
=> Bug 1492033 - partner repacks should be enabled for ESR60

lib/cli_common/cli_common/pulse.py
Fixes #1779.
Works locally, I'm testing it on staging.
=> cli_common: Don't declare RabbitMQ exchange, assume it already exists

lib/cli_common/cli_common/phabricator.py, src/codecoverage/bot/code_coverage_bot/phabricator.py
Secure revisions can't be loaded, so the bot currently fails. We should just print a warning instead.
=> codecoverage/bot: Don't fail when a Phabricator revision is not found

src/codecoverage/bot/code_coverage_bot/artifacts.py, src/codecoverage/bot/code_coverage_bot/chunk_mapping.py, src/codecoverage/bot/tests/test_artifacts.py, src/codecoverage/bot/tests/test_chunk_mapping.py
For example, the entire 'robocop' test suite is available only for Android.
Moreover, some test suites are divided in a smaller/higher number of chunks according to platform (e.g. on Linux we have less chunks than on Windows, as Windows is slower).
=> codecoverage/bot: Make getting chunks platform-specific, as some chunks are only available in a platform and not in another

src/pulselistener/pulselistener/hook.py
Not all pulse messages are supposed to start a task, `parse` returning None is just a way to say "skip this message as it is not relevant", so it's harmless.
=> pulselistener: Don't warn on skipped messages

src/releng_frontend/src/static/trychooser/index.html
Now android/x86-64 and win64/aarch64 are tier-1 platform, so try chooser should have a option for this platforms.
=> Add Android x86_64 and Windows/aarch64 that are tier-1 platfrom

src/shipit/api/shipit_api/api.py, src/shipit/api/shipit_api/models.py
In bug 1496890 we started rendering `clientId`, which is not passed by
default in ship-it. This patch updates the context with the used
clientId just before rendering the jsone template.
=> shipit/api: pass clientId as context

src/codecoverage/bot/code_coverage_bot/codecov.py
Unfortunately we can't assert yet, as there are problems.
In the latest run:
AssertionError: ['obj-firefox/devtools/client/debugger/new/src/components/SecondaryPanes/Frames/index.js', 'obj-firefox/devtools/client/debugger/new/src/components/SecondaryPanes/Frames/Frame.js', 'obj-firefox/devtools/client/debugger/new/src/components/shared/AccessibleImage.js', 'obj-firefox/devtools/client/debugger/new/src/components/SecondaryPanes/Frames/FrameMenu.js', 'obj-firefox/devtools/client/debugger/new/src/components/SecondaryPanes/Frames/Group.js', 'obj-firefox/devtools/client/debugger/new/src/components/shared/Badge.js', 'obj-firefox/devtools/client/debugger/new/src/components/SecondaryPanes/Frames/WhyPaused.js', 'obj-firefox/devtools/client/debugger/new/src/utils/connect.js', …
=> codecoverage/bot: Turn missing files assertion into a warning for now

nix/gecko_env.nix
A new dependency has been added to mozilla-central, llvm-objdump so we must expose this to our nix environment by wrapping it in geckoenv.
=> staticanalysis/bot: Add LLVM_OBJDUMP to geckoenv.

src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/tests/conftest.py
The purpose of this PR is to run clang-format of every file from the patch instead of running it on the diff.
For more details on why we want this behaviour please see https://github.com/mozilla/release-services/issues/1815
Fixes #1815.
=> staticanalysis/bot: Run clang-format on each file from the patch

src/codecoverage/backend/tests/test_coverage.py
Signed-off-by: mandaltapesh <tapesh.mandal@hotmail.com>
The added test function, test_coverage_supported_extensions,  aims to improve the unit test coverage for coverage.py by making a function call to coverage_supported function. It returns True for a path with a valid extension and False if not. So there are two scenarios covered in the unittest one positive (a path with a valid extension) and one negative (a path without a valid extension). And existing test function, test_coverage_supported_extensions_api, which checked for all the supported extensions by making an API call, hence I believe it didn't contribute to unittest coverage.
=> Unittest for coverage_supported

src/releng_frontend/src/static/trychooser/index.html
According to Gecko Decision Task in [this tryserver run](https://treeherder.mozilla.org/#/jobs?repo=try&revision=ca2ece7055ae8cd1b1b44f86ec1f6fe7d17a38e5&selectedJob=224804110), "Exception: Unknown platform(s) [linux64-st-an] specified for try," so presumably it's obsolete and should be removed from the trychooser list of platforms.
=> remove obsolete platform linux64-st-an from trychooser

src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
`./mach clang-format -p path/to/file.cpp` applies changes silently to the working tree. `COMMENT_FAILURE` says "You can run this analysis locally with:" which to me suggests a "show, don't do" command.
By putting in `-s` that instructs `clang-format` to perform the analysis and show the results instead of silently applying them.
To be clear this doesn't change how clang-format is run against patches, just how it's suggested to be run in the helpful reviewbot message.
=> Change clang-format's command message to show, not apply

.gitignore
For whom is working with VSCode as an ide this is a good addition in order to
streamline to working process when VScode begins to creates it's config files
for the current working-space.
=> Add to .gitignore .vscode and all of it's subdirectories

src/staticanalysis/bot/static_analysis_bot/__init__.py, src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/static_analysis_bot/clang/tidy.py, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/coverity/__init__.py, src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py, src/staticanalysis/bot/static_analysis_bot/infer/infer.py, src/staticanalysis/bot/static_analysis_bot/lint.py, src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/static_analysis_bot/workflow.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/mocks/coverity-empty.json, src/staticanalysis/bot/tests/mocks/coverity.json, src/staticanalysis/bot/tests/test_coverity.py
1. It uses the clang infrastructure in order to build the compilation commands that are fed
to the cov translation units for each compilation unit that is part of the analysed diff.
Once the translation has been completed, we forward the translated content to the analysis
machine provided by coverity desktop wrapper.
Once the analysis is performed the results are forwarded to the coverity platform server,
that sends back only the defects that are sane to the patch that was analysed.
2. Migrate the analyzers from Object inhertiance to DefaultAnalyzer.
This permits a better underlying abstractization of the generic interface for the
analyzer.
=> staticanalysis/bot - Add suport for Coverity Analysis reporting for C/C++ compilation units.

src/tooltool/api/tooltool_api/__init__.py, src/tooltool/api/tooltool_api/cli.py
This reverts commit bf1f4e93bd3f54c23a4cebaf844dfa977339c0a4.
Bugzilla URL: https://bugzilla.mozilla.org/show_bug.cgi?id=1524620
=> Revert "tooltool/api: use app.cli.add_command instead of decorator for flask subcommands (#1683)"

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py, src/staticanalysis/bot/tests/mocks/coverity.json
After more testing I've realized that's better to stop taking into consideration the last event from the stack that can be misleading.
=> staticanalysis/bot: For Coverity Analysis do not use the last event from the stack but use the main event marked accordingly.

src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py
Unfortunately the markdown language that is sported by Phabricator is pretty limited so we cannot use fancy syntax in order to have something that is very candy eye.
I've specially made a separate case for as_text for Coveirty Analyzer since I didn't want to change the output of as_markdown that is used to send email hence keeping the consistency of the format of the mails is very important and you don't need that much of the context because you can download the cov_results.json form the job.
=> staticanalysis/bot: Add option to print the full stack of the defect for Coverity analysis

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py
We need compilation units in order to be able to run Coverity. This fix is because of this [issue](https://tools.taskcluster.net/groups/FigmseTSR-KFM-VG5Q6vBA/tasks/FigmseTSR-KFM-VG5Q6vBA/runs/0/logs/public%2Flogs%2Flive.log).
=> staticanalysis/bot: If there are no compilation units abort the Coverity Analysis.

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py
This [issue](https://tools.taskcluster.net/groups/FigmseTSR-KFM-VG5Q6vBA/tasks/FigmseTSR-KFM-VG5Q6vBA/runs/0/logs/public%2Flogs%2Flive.log) triggered my attention where the analysis failed but the exception was not caught in by the analyzer. 
@marco-c what do you think is this something acceptable? We are not really interested into the message of the exception since it's already printed [here](https://github.com/abpostelnicu/release-services/blob/master/lib%2Fcli_common%2Fcli_common%2Fcommand.py#L96).
=> staticanalysis/bot: Coverity catch exceptions of type 'click.ClickException' during the runtime of the analysis.

src/staticanalysis/bot/static_analysis_bot/coverage.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/tests/test_coverage.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
This way we can:
1) Calculate the issue hash (otherwise we fail when calculating it);
2) Remove the hack of considering a nb_lines == -1 as a full-file issue.
=> staticanalysis/bot: Use actual number of lines in the file to identify full file issues

src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
In many cases, we have to do something in-tree. To me, it makes more sense to do that in bugzilla
and keep release services for infra work
=> Use bugzilla instead of release-services for phabricator issues

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/mocks/coverity-silent.json, src/staticanalysis/bot/tests/test_coverity.py
The code review bot has a protocol to filter issues for publication: only issues that `validates()` will be processed for publication on Phabricator.
By loading all issues from the analyzer, we can still display them in the static analysis frontend, and only publish the relevant ones.
=> staticanalysis/bot: Use validation protocol for Coverity issues

src/staticanalysis/bot/static_analysis_bot/coverage.py, src/staticanalysis/bot/tests/mocks/zero_coverage_report.json, src/staticanalysis/bot/tests/test_coverage.py
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1528504.
=> staticanalysis/bot: Ignore header files in the coverage analyzer

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py
This patch is mainly a consequence of [this behaviour](https://tools.taskcluster.net/groups/BAi__NnFQIGMyEFrSCtZKA/tasks/BAi__NnFQIGMyEFrSCtZKA/runs/0/artifacts) that was seen present using the ```IN_PATCH``` analysis method.
=>  staticanalysis/bot: For CoverityIssue override `is_publishable` and publish only if it's a local issue.

src/shipit/api/setup.py
I was confused by the old URL not resolving on my machine
=> shipit/api: Update production URL to the right one

src/staticanalysis/frontend/src/Choice.vue, src/staticanalysis/frontend/src/Task.vue
* Adds missing coverity fields in issue details
* Display publishable issues on top
* Filter issues by publishable status
* Filter issues by path
* Filter issues by analyzer
* Filters are set in the url and are shareable
It's deploying on testing, here is [a good example](https://static-analysis.testing.moz.tools/#/task/YJv8RMoVQfWeQRanN_Tv-A)
=> Nicer report page to debug static analysis reports

src/staticanalysis/frontend/src/Tasks.vue, src/staticanalysis/frontend/src/store.js
While working on #1754, i noticed a bad behaviour in the SA frontend: only the last analysis task of a revision was displayed !
This [sample revision](https://phabricator.services.mozilla.com/D19250) has 16 diffs, and 5 analysis tasks (when looking in papertrail logs). But the static analysis dashboard in production only show the one when looking for the revision phid:
So i made that PR to do the following:
1. Use the `phabricator.diff` route (indexing by diff) instead of `phabricator` (indexing by revision)
2. Display the revision phid & id on the tasks list
3. Allow searching by revision ID (much easier to find than the revision PHID)
Which gives us a way better state:
=> staticanalysis/frontend: Search by revision ID and load all tasks for diff

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py, src/staticanalysis/bot/tests/test_coverity.py
The `CoverityIssue` class was always reporting an issue as **publishable**, so the static analysis frontend displayed all issues as published in production.
This PR sends the correct pubilcation status, with detailed informations in the mail & TC Index.
=> staticanalysis/bot: Fix CoverityIssue reported state

src/staticanalysis/bot/default.nix, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/config.py
I renamed `cache_root` to `work_dir` as it's still useful for developers to specify a static path
Fixes #1923.
=> Remove mercurial clone cache

lib/cli_common/cli_common/log.py, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/workflows/local.py
Sample output:
```
static_analysis_bot.config: Loaded configuration from mozilla-central (timestamp='2019-03-04 16:49:01')
datadog.threadstats: Starting flush thread with interval 10.
static_analysis_bot.report.mail: Mail report enabled (emails=['babadie@mozilla.com', 'sledru@mozilla.com', 'andi@mozilla.com'] timestamp='2019-03-04 16:49:01')
cli_common.phabricator: Authenticated on https://phabricator.services.mozilla.com/api/ as Code Review Bot (timestamp='2019-03-04 16:49:02')
static_analysis_bot.workflows.base: Skipping taskcluster indexing (rev='Phabricator #66043 - PHID-DIFF-uhnq6b5tekvkdhyiuzay' state='started' timestamp='2019-03-04 16:49:04')
static_analysis_bot.workflows.local: New static analysis (taskcluster_task='local instance' taskcluster_run=0 channel='staging' …
```
=> Display time & logs for mercurial clone

src/shipit/api/shipit_api/cli.py
Instead of syncing all products, it'd be better to limit the sync to a
particular product. We have already switched Firefox and Co to v2, so
there is no reason to sync them again and again.
=> shipit/api: sync by product prefix

src/staticanalysis/bot/static_analysis_bot/workflows/base.py, src/staticanalysis/bot/tests/test_workflow.py, src/staticanalysis/frontend/src/Tasks.vue, src/staticanalysis/frontend/src/routes.js, src/staticanalysis/frontend/src/store.js
I want to display efficiently all the static analysis tasks for a given phabricator revision. Currently we have to load all the tasks in the index, and filter the output.
A better usage of taskcluster index would allow to list directlty the tasks in a given namespace (by indexing the task in a sub-namespace)
In the end, an url like: `https://static-analysis.moz.tools/#/rev/D12345` should list all the tasks from `D12345`, so that a developer can view the current state on our side.
We could then **always** post a comment on the revision during the first task to display the link.
EDIT: after discussion, we won't post automatically the link.
=> List static analysis tasks for a phabricator revision

lib/please_cli/please_cli/config.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1532843 for the details
=> shipit/api: don't push to mozilla/shipitbackend

lib/please_cli/please_cli/config.py
Needed for deploying on cloudops
=> setup: deploy pulselistener on Dockerhub with stable tags.

src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/test_reporter_debug.py, src/staticanalysis/bot/tests/test_reporter_mail.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py, src/staticanalysis/bot/tests/test_revisions.py
This was initially made in #1953 , and runs on testing.
It's needed to load the Phabricator revision from a task triggered by pulse in the try workflow
=> Load diff_phid from try task as early as possible

lib/cli_common/cli_common/cli.py
This is the followup of #1896 to ease developer usage around Taskcluster credentials.
=> cli_common: Automatically use the user credentials when available 

src/shipit/api/shipit_api/models.py, src/shipit/api/shipit_api/tasks.py
In version 2.0.0 slugid started using strings instead of bytes.
Quote:
"Slugs are generated with the interpreter's default string type. On
Python 2, these are byte strings.  On Python 3, these are unicode
strings."
=> shipit/api: fix slugid usage

src/shipit/api/shipit_api/product_details.py
The links are currently relative, which works for the top level index.html, but not for any of the index.html in subfolders. This just makes them absolute.
=> shipit: add / to folder hrefs

lib/cli_common/cli_common/cli.py
While developing #1975, i used an older version of local config... that does not match the format currently used !
=> cli_common: Fix variable names for local config

lib/cli_common/cli_common/phabricator.py, src/pulselistener/pulselistener/mercurial.py, src/pulselistener/tests/conftest.py, src/pulselistener/tests/mocks/phabricator/search-PHID-DIFF-solo.json, src/pulselistener/tests/mocks/phabricator/search-PHID-DIFF-xxxx-PHID-DIFF-test123.json, src/pulselistener/tests/test_mercurial.py
As requested on IRC, i modified the messages for our Try pushes commits by reusing the original message from developer. In most cases the Phabricator revision URL is already present in that message.
Fixes #1990 .
=> Nicer Try commit messages

lib/cli_common/cli_common/phabricator.py, src/pulselistener/pulselistener/listener.py, src/pulselistener/pulselistener/mercurial.py, src/pulselistener/pulselistener/phabricator.py
This PR enhances the basic webhook workflow for pulselistener, and allows long security policy  checks, while replying immediatley to HTTP requests
1. An HTTP POST query is made towards pulselistener by Harbormaster, to initiate the build. Pulselistener must reply immediately.
2. The build information are stored in a queue
3. The queue is processed regularly, and check the current builds security policy
3.a. If a build is secured, the check is retried N times with a wait period between each checks (without locking other processes). When the max retries is exceeded, the build is marked as `Secured`, and the Harbormaster target updated as **fail**.
3.b. If a build is public, it's processed by the `trigger_task` (normally using Try pushes). The build is marked as `Public` and the …
=> Better webhook flow

lib/cli_common/cli_common/phabricator.py, src/pulselistener/pulselistener/listener.py, src/pulselistener/pulselistener/mercurial.py, src/staticanalysis/bot/static_analysis_bot/revisions.py
- ~~Send Taskcluster link to Phabricator~~ :crying_cat_face: :it: 
- Provides the Harbormaster Target PHID to the SA task to avoid looking for it (and potentially missing it)
=> Update Harbormaster status when using direct Taskcluster tasks

nix/gecko_env.nix
@garbas After updating the nixpkgs-channels revision, i get errors about missing `flake8` in the PATH (but it's installed accroding to the build log). Any idea ?
Also, how can i get the `sha256_tarball` value ?
=> Upgrade clang 7 to 8

src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/tests/conftest.py, src/staticanalysis/bot/tests/test_reporter_mail.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
As per [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1530698) we should provide actionable info for clang-tidy and clang-format.
=> staticanalysis/bot: Consider having reviewbot provide more actionable clang-format and clang-tidy.

src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/tests/test_clang.py
Fix [this bug](https://tools.taskcluster.net/groups/MQmu293iSrWf8d52Fxr7UQ/tasks/MQmu293iSrWf8d52Fxr7UQ/runs/0/logs/public%2Flogs%2Flive.log)
=> staticanalysis/bot: Fix clang-format bug when no touched/added line in patch

lib/cli_common/cli_common/phabricator.py, src/pulselistener/pulselistener/mercurial.py, src/staticanalysis/bot/static_analysis_bot/__init__.py, src/staticanalysis/bot/static_analysis_bot/clang/tidy.py, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/static_analysis_bot/workflows/base.py, src/staticanalysis/bot/static_analysis_bot/workflows/remote.py, src/staticanalysis/bot/tests/test_remote.py
Modifications that should be in a few different PRs:
1. Only run SA local workflow when analyzers are set (i only want the remote workflow !)
2. Use the build target phid instead of the diff phid in the `try_task_config.json` when pushing to try
3. Use that same build target phid in the code review publication task to retrieve the infos from the diff (instead of doing the opposite)
4. Fix a bug in `ClangTidyIssue` building when reliability is not available on remote output
=> Fixes to run code review in shadow mode for Try

src/pulselistener/pulselistener/listener.py, src/pulselistener/pulselistener/mercurial.py, src/pulselistener/tests/conftest.py, src/pulselistener/tests/mocks/phabricator/artifact-PHID-HMBT-somehash.json, src/pulselistener/tests/test_mercurial.py
I forgot to add that option before the release.
=> pulselistener: Add option to disable treeherder link publication

src/staticanalysis/bot/static_analysis_bot/coverity/coverity.py, src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/tests/test_remote.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
=> staticanalysis/bot: Clean coverity paths in remote issues.

src/staticanalysis/bot/static_analysis_bot/clang/format.py, src/staticanalysis/bot/static_analysis_bot/task.py
To avoid [this issue](https://tools.taskcluster.net/groups/VVI337njQmKMBDfR7_w8ow/tasks/VVI337njQmKMBDfR7_w8ow/runs/0/logs/public%2Flogs%2Flive.log)
=> staticanalysis/bot: Support empty clang-format patches

lib/please_cli/please_cli/config.py
there are some issues with the current version (openssl!). Let's disable it for now.
=> scriptworker/shipitscript: disable deployments

lib/cli_common/cli_common/phabricator.py, src/pulselistener/pulselistener/cli.py, src/pulselistener/pulselistener/listener.py, src/pulselistener/pulselistener/mercurial.py, src/pulselistener/pulselistener/phabricator.py, src/pulselistener/tests/conftest.py, src/pulselistener/tests/mocks/phabricator/message-PHID-somehash-fail-unit.json, src/pulselistener/tests/test_mercurial.py
Fixes #1542 by (ab)using Phabricator Unit tests results.
This PR does a bit of cleanup first, by removing the deprecated phabricator polling method. This allows me to require `build_target_phid` since the beginning instead of relying on a key in a dict.
I played a bit with Phabricator options, and [here is the final result](https://phabricator-dev.allizom.org/D1146)
=> Warn developer when we fail to apply its patch

nix/lib/default.nix, src/tooltool/api/default.nix, src/tooltool/api/tooltool_api/__init__.py, src/tooltool/api/tooltool_api/api.py, src/tooltool/api/tooltool_api/tooltool.py.download
as http://tooltool.mozilla-releng.net/tooltool.py
=> tooltool/api: provide client via api

src/pulselistener/pulselistener/listener.py
Got a nice dummy crash on staging
[Manual Deployment](https://tools.taskcluster.net/groups/ASC9k9vcRPSOXkYZqnB-og/tasks/ASC9k9vcRPSOXkYZqnB-og/details) on staging for test.
=> pulselistener: Fix old variable usage

src/staticanalysis/bot/static_analysis_bot/tasks/coverity.py, src/staticanalysis/bot/tests/test_coverity.py
In order to avoid bugs like [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1542163) we should also call the base method of ```is_publishable```.
=> staticanalysis/bot: For Coverity analysis when calling is_publishable also use the method defined in the base class.

src/staticanalysis/bot/static_analysis_bot/tasks/clang_tidy.py, src/staticanalysis/bot/static_analysis_bot/tasks/coverity.py, src/staticanalysis/bot/tests/test_clang.py, src/staticanalysis/bot/tests/test_coverity.py, src/staticanalysis/bot/tests/test_remote.py
Right now the message is a little bit confusing, since it leads the developer to believe that a `low` index refers to a low probability of the checker having `false-positives`.
=> staticanalysis/bot: Change the wording for `reliability` index in order to make less prone to confusion.

src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/tasks/coverity.py, src/staticanalysis/bot/tests/test_coverity.py, src/staticanalysis/bot/tests/test_remote.py
Since we are no longer using local analysis for `Coverity` we should remove the rest of the references.
=> staticanalysis/bot: Cleanup Coverity data that was used for local analysis. Fixes #2082

src/docs/projects/staticanalysis-bot.rst
* Dev environment without Docker/nix
* Simplified auth setup
* Use taskcluster ids instead of Phabricator ids
[Rendered version](https://github.com/mozilla/release-services/blob/d259bcc0c74608bf6c64f0f004d892632eba9d11/src/docs/projects/staticanalysis-bot.rst) should be easier to read
=> docs: Update staticanalysis/bot doc after try migration

src/staticanalysis/bot/static_analysis_bot/report/base.py, src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/tests/test_reporter_phabricator.py
In order to make defects more tighten to the diff id we should also publish the diff id near the defects summary for each analyser.
=> staticanalysis/bot: Append diff-id to the linting messages.

src/pulselistener/pulselistener/listener.py
I noticed a crash on pulselistener when a revision is secured, the hook tries to update the revision... but it has no access to it !
=> pulselistener: Avoid updating a secured revision

lib/cli_common/cli_common/gcp.py
Fix for the backend issue:
```
{
"detail": "'Missing bucket in GOOGLE_CLOUD_STORAGE'",
"instance": "about:blank",
"status": 500,
"title": "'Missing bucket in GOOGLE_CLOUD_STORAGE'",
"type": "about:blank"
}
```
=> cli_common: Do not remove bucket from service account secret.

src/codecoverage/bot/tools/covdir_gen.py
Add 2 options to `tools/covdir_gen.py`:
1. `--unique-dates` will trigger only one task per day
2. `--group=XXX` allow specifying an existing taskcluster group with code coverage generation tasks, and will skip the existing commits: this permits to create small batches of tasks in a same group:
For example on prod, this command will add the next 3 days of code coverage [not yet processed in the task group](https://tools.taskcluster.net/groups/MNmrH4EXSx6zmohMfWVTxw).
```shell
python tools/covdir_gen.py --unique-dates --nb-tasks=3 --group=MNmrH4EXSx6zmohMfWVTxw
```
=> Add option to trigger one task per day.

src/staticanalysis/bot/requirements.nix, src/staticanalysis/bot/requirements.txt, src/staticanalysis/bot/static_analysis_bot/cli.py, src/staticanalysis/bot/static_analysis_bot/config.py, src/staticanalysis/bot/static_analysis_bot/report/__init__.py, src/staticanalysis/bot/static_analysis_bot/report/debug.py, src/staticanalysis/bot/static_analysis_bot/report/mail.py, src/staticanalysis/bot/static_analysis_bot/report/phabricator.py, src/staticanalysis/bot/static_analysis_bot/revisions.py, src/staticanalysis/bot/static_analysis_bot/tasks/base.py, src/staticanalysis/bot/static_analysis_bot/tasks/clang_format.py, src/staticanalysis/bot/static_analysis_bot/tasks/clang_tidy.py, src/staticanalysis/bot/static_analysis_bot/tasks/coverage.py, src/staticanalysis/bot/static_analysis_bot/tasks/coverity.py, src/staticanalysis/bot/static_analysis_bot/tasks/infer.py, src/staticanalysis/bot/static_analysis_bot/tasks/lint.py, src/staticanalysis/bot/static_analysis_bot/tools/log.py, src/staticanalysis/bot/static_analysis_bot/workflow.py
* Removes deprecated MOZDEF support
* Keep publishing on papertrail & sentry
* A bit nicer format (colors on console when available, better display of level, time & module)
* Removes `cli_common` usage as it was the last part using it.
=> Use structlog & logbook

src/shipit/frontend/src/configs/production.js
Follows https://github.com/mozilla/release-services/pull/2155 up
r? @rail 
I'd need to get this landed before the next go-to-build on Thursday. Do you think it can be deployed by then?
=> Bug 1558507 - Move Fennec Beta to mozilla-esr68

src/pulselistener/pulselistener/mercurial.py, src/pulselistener/tests/test_mercurial.py
On new NSS patches, pulselistener will apply the stack of patches, then add a commit with `try_task_config.json` with the following content:
```json
{
"version": 2,
"parameters": {
"code-review": {
"phabricator-build-target": "PHID-HMBT-xxx123",
}
}
}
```
This content is using the same format as [mozilla-central try v2](https://firefox-source-docs.mozilla.org/main/latest/taskcluster/taskcluster/try.html#complex-configuration)
The commit message will have the try syntax setup in the Taskcluster secret (`try: -p none -t coverity` for NSS)
=> pulselistener: Write try_task_config.json for NSS too

src/pulselistener/pulselistener/mercurial.py
Pulselistener needs a setting to setup the repo's name as it's used by try/treeherder.
Right now, when an NSS patch is applied, the url reported on phabricator is :
`https://treeherder.mozilla.org/#/jobs?repo=try&revision=548a258b4d8e2cd29532cda96a25ef8da1ce39a2`
where it should be `https://treeherder.mozilla.org/#/jobs?repo=nss-try&revision=548a258b4d8e2cd29532cda96a25ef8da1ce39a2` (`nss-try` instead of `try`)
=> pulselistener: Allow configuration of repo name for treeherder links

src/tooltool/client/MANIFEST.in, src/tooltool/client/test.sh, src/tooltool/client/test_tooltool.py, src/tooltool/client/tooltool.py, src/tooltool/client/tox.ini, src/tooltool/client/validate.sh
the idea behind this PR is to _only_ add python 3 support without doing any bigger refactoring. switching to more up to date python tooling should be done in a separate PR, once all tooltool projects are outside this repository.
I could not just depend on six or future package in tooltool.py since tooltool.py is suppose to be without any dependencies.
=> tooltool/client: py3 support added (still keeping py2.7 support)

src/shipit/api/shipit_api/api.py, src/shipit/api/shipit_api/product_details.py, src/shipit/api/shipit_api/release.py
In gecko 68 we started building Fennec using mozilla-esr68 and beta
numbers became something like 68.1b1. `FirefoxVersion` won't accept this
kind of versions. It would be better to use per product classes to parse
versions.
=> shipit/api: parse version per product

src/shipit/api/settings.py, src/shipit/api/setup.py, src/shipit/api/shipit_api/api.py, src/shipit/api/shipit_api/api.yml, src/shipit/api/shipit_api/cli.py
* Remove the old sync API, shipit v1 is EOL
* Add ability to import releases. It is very useful for local
development
=> shipit/api: import releases from API

src/shipit/api/shipit_api/product_details.py
When we have 2 ESR releases active at the same time, we want them both
to be in `firefox_primary_builds.json`
=> shipit/api: add ESR_NEXT in primary_builds.json

src/pulselistener/pulselistener/listener.py, src/pulselistener/tests/test_code_coverage_listener.py
Needed to trigger the new codecoverage hooks.
=> pulselistener: Support custom hookGroupId

src/pulselistener/pulselistener/lib/bus.py
Without this sleep call, the mercurial worker does not start cloning the repositories, and pulselistener never triggers the builds later on.
=> Fix boot sequence

src/shipit/api/shipit_api/release.py, src/shipit/api/shipit_api/tasks.py, src/shipit/api/tests/test_release.py
context:
wsmwk> mhentges: i'm getting an auth failure in shipit trying to "start tracking" for thunderbird
bhearsum> i found the exception for the thunderbird issue: https://gist.github.com/mozbhearsum/2ab0ceadf1122c18140ff16b75916bfa
closemozbhearsum — 8 Aug 2019
13:22:52 
<•bhearsum> (it was on Sentry, for those with acccess: https://sentry.prod.mozaws.net/operations/mozilla-releng-services/issues/6127311/?query=is:unresolved%20is:unassigned)
14:47:32 
<•jlund> should thunderbird have an rc flavour? Does it push release builds to beta first?
14:47:37 it's not in https://github.com/mozilla/release-services/blob/4567698690d6cce5bf2a685c04021774125294cd/src/shipit/api/shipit_api/config.py#L432
14:47:45 but code thinks it should be: …
=> adds product to is_rc for thunderbird edge case

src/shipit/api/requirements.nix, src/shipit/api/requirements_frozen.txt
This will let shipit show new fennec versions, that are introduced in
0.3.4
=> shipit/api: bump mozilla-version to 0.4.1

lib/please_cli/please_cli/config.py
As the version from #2244 is currently in use, and should be the last deployment.
=> setup: Disable pulselistener deploy on heroku & remove from dockerhub.

lib/please_cli/please_cli/config.py, nix/tools/mercurial.nix, src/pulselistener/pulselistener/code_review.py, src/pulselistener/pulselistener/lib/bus.py, src/pulselistener/pulselistener/lib/mercurial.py, src/pulselistener/pulselistener/lib/pulse.py, src/pulselistener/pulselistener/lib/utils.py, src/pulselistener/pulselistener/lib/web.py, src/pulselistener/pulselistener/listener.py, src/pulselistener/requirements.nix, src/pulselistener/requirements.txt, src/pulselistener/requirements_frozen.txt, src/pulselistener/tests/conftest.py, src/pulselistener/tests/test_code_coverage_listener.py
... and use up-to-date version-control-tools
* Batch_checkout (as before)
* Robustcheckout
* Default Hg clone
This change is not mandatory, as i made it to debug pulselistener crashes on a day where the HG payload on the cdn was corrupted (when i understood the issue, i reported it on #vcs, it was fixed in a few minutes…)
But, having robustcheckout is nice to have for smaller repos like nss
It’s only used for the incoming HTTP notifications. As it’s limited in scope, it was simple to implement (dump the pickled objects in a redis list). But the benefits are immediate: even if pulselistener crashes, we do not lose anymore the build notifications from the previous instances
The web process was not stopped on crashes (only on KeyboardInterrupt…) I simplified the old run_consumer function …
=> Pulselistener fixes

src/shipit/api/shipit_api/api.py, src/shipit/api/shipit_api/models.py, src/shipit/api/shipit_api/product_details.py, src/shipit/api/shipit_api/release.py, src/shipit/api/tests/test_release.py
Reverts mozilla/release-services#2231
From IRC:
> weird, 70.0b4 is set up as an rc release D:
=> Revert "Centralize version parsing in mozilla-version 0.4.x"
